/**
 * Exercise Seed Script v2
 *
 * Adds comprehensive exercise library covering all muscle groups.
 * Skips any exercises that already exist in the database by name.
 *
 * Run with: npx ts-node prisma/seed-exercises-v2.ts
 */

import {
  PrismaClient,
  MuscleGroup,
  EquipmentType,
  MovementPattern,
  DifficultyLevel,
  ExerciseType,
  MetricType,
} from '@prisma/client'

const prisma = new PrismaClient()

const B = EquipmentType.BARBELL
const DB = EquipmentType.DUMBBELL
const KB = EquipmentType.KETTLEBELL
const M = EquipmentType.MACHINE
const C = EquipmentType.CABLE
const BW = EquipmentType.BODYWEIGHT
const RB = EquipmentType.RESISTANCE_BAND
const TRX = EquipmentType.TRX
// const CARDIO = EquipmentType.CARDIO_EQUIPMENT

const CHEST = MuscleGroup.CHEST
const UPPER_BACK = MuscleGroup.UPPER_BACK
const LATS = MuscleGroup.LATS
const LOWER_BACK = MuscleGroup.LOWER_BACK
const TRAPS = MuscleGroup.TRAPS
const FRONT_DELTS = MuscleGroup.FRONT_DELTS
const SIDE_DELTS = MuscleGroup.SIDE_DELTS
const REAR_DELTS = MuscleGroup.REAR_DELTS
const BICEPS = MuscleGroup.BICEPS
const TRICEPS = MuscleGroup.TRICEPS
const FOREARMS = MuscleGroup.FOREARMS
const QUADS = MuscleGroup.QUADS
const HAMSTRINGS = MuscleGroup.HAMSTRINGS
const GLUTES = MuscleGroup.GLUTES
// const CALVES = MuscleGroup.CALVES
const CORE = MuscleGroup.CORE
// const ABDUCTORS = MuscleGroup.ABDUCTORS
// const ADDUCTORS = MuscleGroup.ADDUCTORS
// const FULL_BODY = MuscleGroup.FULL_BODY

const BEG = DifficultyLevel.BEGINNER
const INT = DifficultyLevel.INTERMEDIATE
const ADV = DifficultyLevel.ADVANCED

const SMALL = ExerciseType.SMALL
const MEDIUM = ExerciseType.MEDIUM
const LARGE = ExerciseType.LARGE
const STABILITY = ExerciseType.STABILITY
// const CARDIO_TYPE = ExerciseType.CARDIO

const WR = MetricType.WEIGHT_REPS
const REPS = MetricType.REPS
const DUR = MetricType.DURATION
// const DIST_DUR = MetricType.DISTANCE_DURATION
// const W_DUR = MetricType.WEIGHT_DURATION
// const W_DIST = MetricType.WEIGHT_DISTANCE
const CWR = MetricType.COUNTER_WEIGHT_REPS

const PUSH = MovementPattern.PUSH
const PULL = MovementPattern.PULL
// const SQUAT = MovementPattern.SQUAT
const HINGE = MovementPattern.HINGE
// const CARRY = MovementPattern.CARRY
// const CORE_PAT = MovementPattern.CORE
// const LUNGE = MovementPattern.LUNGE
const OLYMPIC = MovementPattern.OLYMPIC

const T = true

type ExerciseSeed = {
  name: string
  description?: string
  primaryMuscleGroup: MuscleGroup
  secondaryMuscleGroups: MuscleGroup[]
  equipmentType: EquipmentType
  movementPattern: MovementPattern
  difficultyLevel: DifficultyLevel
  exerciseType: ExerciseType
  metricType: MetricType
  instructions: string[]
  isDefault: boolean
}

// ============================================================================
// CHEST
// ============================================================================

const chestExercises: ExerciseSeed[] = [
  {
    name: 'Decline Barbell Bench Press',
    description: 'Lower chest focused bench press on a decline bench',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [TRICEPS, FRONT_DELTS],
    equipmentType: B,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Set bench to 15–30 degree decline, secure feet under pads',
      'Grip bar slightly wider than shoulder-width',
      'Unrack and lower bar to lower chest with control',
      'Press explosively until arms are fully extended',
      'Keep shoulder blades retracted throughout the movement',
    ],
    isDefault: T,
  },
  {
    name: 'Incline Dumbbell Press',
    description: 'Upper chest press using dumbbells on an incline bench',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [FRONT_DELTS, TRICEPS],
    equipmentType: DB,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Set bench to 30–45 degree incline',
      'Hold dumbbells at chest level with palms facing forward',
      'Press dumbbells up and slightly inward until arms are extended',
      'Lower with control to starting position, allowing a slight stretch',
      'Keep core braced and feet flat on the floor',
    ],
    isDefault: T,
  },
  {
    name: 'Decline Dumbbell Press',
    description: 'Lower chest press using dumbbells on a decline bench',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [TRICEPS, FRONT_DELTS],
    equipmentType: DB,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Set bench to 15–30 degree decline and secure feet',
      'Hold dumbbells at chest level, elbows at 45-degree angle',
      'Press dumbbells up until arms are fully extended',
      'Lower with control to stretch position below chest level',
    ],
    isDefault: T,
  },
  {
    name: 'Dumbbell Floor Press',
    description: 'Chest press performed lying on the floor, limiting range of motion',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [TRICEPS, FRONT_DELTS],
    equipmentType: DB,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Lie flat on the floor with knees bent and feet planted',
      'Hold dumbbells at chest level with elbows resting on the floor',
      'Press dumbbells up until arms are fully extended',
      'Lower until elbows touch the floor, then repeat',
      'The floor limits shoulder range of motion, reducing injury risk',
    ],
    isDefault: T,
  },
  {
    name: 'Machine Chest Press',
    description: 'Chest press using a guided machine for stability',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [TRICEPS, FRONT_DELTS],
    equipmentType: M,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Adjust seat so handles are at mid-chest height',
      'Grip handles with palms facing forward or neutral',
      'Push handles forward until arms are nearly extended',
      'Return to starting position with control',
      'Keep back pressed against the pad throughout',
    ],
    isDefault: T,
  },
  {
    name: 'Hammer Strength Chest Press',
    description: 'Plate-loaded machine press with independent arm movement',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [TRICEPS, FRONT_DELTS],
    equipmentType: M,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Adjust seat so handles align with mid-chest',
      'Grip handles and plant feet firmly on the platform',
      'Press handles forward and slightly inward, squeezing chest',
      'Lower with control until you feel a stretch in the chest',
      'Each arm moves independently for balanced development',
    ],
    isDefault: T,
  },
  {
    name: 'Cable Chest Press',
    description: 'Standing or seated chest press using cable machine',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [TRICEPS, FRONT_DELTS],
    equipmentType: C,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Set pulleys to chest height on both sides',
      'Stand in the center with a staggered stance',
      'Grip handles and extend arms forward at chest level',
      'Return handles back with control, keeping slight elbow bend',
      'Maintain upright torso and braced core throughout',
    ],
    isDefault: T,
  },
  {
    name: 'Single Arm Cable Chest Press',
    description: 'Unilateral cable press targeting one side of the chest at a time',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [TRICEPS, FRONT_DELTS, CORE],
    equipmentType: C,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Set cable pulley to chest height on one side',
      'Stand sideways to the machine with a staggered stance',
      'Grip handle with the near hand, brace core to resist rotation',
      'Press handle forward until arm is nearly extended',
      'Return with control and repeat, then switch sides',
    ],
    isDefault: T,
  },
  {
    name: 'Smith Machine Bench Press',
    description: 'Guided barbell bench press using a Smith machine',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [TRICEPS, FRONT_DELTS],
    equipmentType: M,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Position flat bench under Smith machine bar',
      'Lie flat with eyes under the bar, grip slightly wider than shoulders',
      'Unhook the bar by rotating and lower to mid-chest',
      'Press bar up until arms are extended, then re-rack with a twist',
    ],
    isDefault: T,
  },
  {
    name: 'Smith Machine Incline Bench Press',
    description: 'Guided incline bench press on a Smith machine targeting upper chest',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [FRONT_DELTS, TRICEPS],
    equipmentType: M,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Set bench to 30–45 degree incline under the Smith machine',
      'Grip bar at shoulder-width and unhook',
      'Lower to upper chest with control',
      'Press up until arms are fully extended',
    ],
    isDefault: T,
  },
  {
    name: 'Smith Machine Decline Bench Press',
    description: 'Guided decline bench press on a Smith machine targeting lower chest',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [TRICEPS, FRONT_DELTS],
    equipmentType: M,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Set bench to 15–30 degree decline under Smith machine, secure feet',
      'Grip bar at shoulder-width and unhook',
      'Lower to lower chest with control',
      'Press up until arms are fully extended',
    ],
    isDefault: T,
  },
  {
    name: 'Guillotine Press',
    description: 'Wide-grip bench press with bar lowered to the neck for upper chest stretch',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [FRONT_DELTS, TRICEPS],
    equipmentType: B,
    movementPattern: PUSH,
    difficultyLevel: ADV,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Lie flat on bench with a wide grip on the bar',
      'Lower bar slowly to the neck or upper chest area',
      'Keep elbows flared out wide to maximize upper chest stretch',
      'Press bar back up with control — use light weight and caution',
      'This exercise places high stress on the shoulder joint',
    ],
    isDefault: T,
  },
  {
    name: 'Spoto Press',
    description: 'Paused bench press stopping 1–2 inches above the chest without touching',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [TRICEPS, FRONT_DELTS],
    equipmentType: B,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Set up as for a standard barbell bench press',
      'Lower bar to just 1–2 inches above the chest',
      'Pause for 1–2 seconds without touching the chest or relaxing tension',
      'Press bar up explosively to lockout',
      'Builds chest strength and eliminates bounce off the chest',
    ],
    isDefault: T,
  },
  {
    name: 'Wide Grip Barbell Bench Press',
    description: 'Barbell bench press with grip wider than shoulder-width for chest emphasis',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [FRONT_DELTS, TRICEPS],
    equipmentType: B,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Lie flat on bench and grip bar 1–2 inches wider than shoulder-width on each side',
      'Lower bar to mid-chest with elbows flared slightly',
      'Press bar up until arms are fully extended',
      'Keep shoulder blades retracted throughout',
    ],
    isDefault: T,
  },
  {
    name: 'Dumbbell Fly',
    description: 'Chest isolation exercise opening and closing arms in an arc',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [],
    equipmentType: DB,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Lie flat on bench holding dumbbells above chest with slight elbow bend',
      'Lower dumbbells out to sides in a wide arc until a stretch is felt',
      'Squeeze chest and bring dumbbells back together in an arc',
      'Do not fully lock out or let dumbbells touch at the top',
    ],
    isDefault: T,
  },
  {
    name: 'Incline Dumbbell Fly',
    description: 'Fly movement on an incline bench targeting the upper chest',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [FRONT_DELTS],
    equipmentType: DB,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Set bench to 30–45 degree incline',
      'Hold dumbbells above upper chest with slight elbow bend',
      'Open arms wide in an arc, lowering until chest stretches',
      'Squeeze upper chest and bring dumbbells back together',
    ],
    isDefault: T,
  },
  {
    name: 'Decline Dumbbell Fly',
    description: 'Fly movement on a decline bench targeting the lower chest',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [],
    equipmentType: DB,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Set bench to 15–30 degree decline and secure feet',
      'Hold dumbbells above lower chest with slight elbow bend',
      'Lower dumbbells out to sides in a wide arc',
      'Squeeze lower chest and return dumbbells to starting position',
    ],
    isDefault: T,
  },
  {
    name: 'Cable Fly (High to Low)',
    description: 'Cable fly with pulleys set high, targeting the lower chest fibers',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [],
    equipmentType: C,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Set both pulleys to the highest position',
      'Stand in the center, grip handles with palms facing down',
      'With slight elbow bend, pull handles down and together in front of hips',
      'Squeeze lower chest at the bottom, then return with control',
      'Lean slightly forward for better range of motion',
    ],
    isDefault: T,
  },
  {
    name: 'Cable Fly (Low to High)',
    description: 'Cable fly with pulleys set low, targeting the upper chest fibers',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [FRONT_DELTS],
    equipmentType: C,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Set both pulleys to the lowest position',
      'Stand in the center, grip handles with palms facing up',
      'With slight elbow bend, pull handles up and together at chest height or above',
      'Squeeze upper chest at the top, then return with control',
    ],
    isDefault: T,
  },
  {
    name: 'Cable Fly (Mid Chest)',
    description: 'Cable fly with pulleys at chest height targeting the middle chest fibers',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [],
    equipmentType: C,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Set both pulleys to chest height',
      'Stand in the center with a slight forward lean',
      'Grip handles and extend arms out to the sides with a slight elbow bend',
      'Bring handles together in front of chest in an arc',
      'Squeeze chest at the peak, then return with control',
    ],
    isDefault: T,
  },
  {
    name: 'Pec Deck Machine Fly',
    description: 'Machine-based fly isolating the chest with guided arm movement',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [],
    equipmentType: M,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Adjust seat so arms are parallel to the floor when gripping pads',
      'Place forearms or hands against the arm pads',
      'Squeeze chest to bring arms together in front of body',
      'Return arms with control until you feel a full chest stretch',
    ],
    isDefault: T,
  },
  {
    name: 'Plate Squeeze Press',
    description: 'Chest press while squeezing weight plates together to maximize chest activation',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [TRICEPS],
    equipmentType: BW,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Lie on a flat bench holding weight plates pressed together between palms',
      'Keep plates pressed firmly together throughout the entire set',
      'Press plates up from chest level until arms are nearly extended',
      'Lower with control, maintaining plate tension',
    ],
    isDefault: T,
  },
  {
    name: 'Weighted Push-Up',
    description: 'Standard push-up with a weight plate on the upper back for added resistance',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [TRICEPS, FRONT_DELTS, CORE],
    equipmentType: BW,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Have a partner place a weight plate on your upper back',
      'Start in high plank with hands slightly wider than shoulders',
      'Lower chest to just above the floor with control',
      'Push back up to starting position',
      'Maintain a straight body line from head to heels',
    ],
    isDefault: T,
  },
  {
    name: 'Deficit Push-Up',
    description: 'Push-up performed with hands elevated to increase range of motion',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [TRICEPS, FRONT_DELTS, CORE],
    equipmentType: BW,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: REPS,
    instructions: [
      'Place hands on elevated platforms (dumbbells or push-up handles)',
      'Start in high plank position with hands at chest level',
      'Lower chest below hand level for an increased stretch',
      'Push back up to starting position',
      'Greater range of motion increases chest stretch and stimulus',
    ],
    isDefault: T,
  },
  {
    name: 'Ring Push-Up',
    description: 'Push-up using gymnastic rings for increased instability and chest activation',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [TRICEPS, FRONT_DELTS, CORE],
    equipmentType: TRX,
    movementPattern: PUSH,
    difficultyLevel: ADV,
    exerciseType: MEDIUM,
    metricType: REPS,
    instructions: [
      'Set rings at a low height above the floor',
      'Grip rings and get into push-up position with arms extended',
      'Lower chest to ring height while maintaining control of rings',
      'Press back up and turn palms outward at the top for peak contraction',
      'The instability of rings increases muscle activation significantly',
    ],
    isDefault: T,
  },
  {
    name: 'Archer Push-Up',
    description: 'Unilateral push-up variation that shifts load to one arm at a time',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [TRICEPS, FRONT_DELTS],
    equipmentType: BW,
    movementPattern: PUSH,
    difficultyLevel: ADV,
    exerciseType: MEDIUM,
    metricType: REPS,
    instructions: [
      'Start in a wide push-up position with arms spread far apart',
      'Lower toward one arm while keeping the other arm straight',
      'The straight arm acts as a support as you lower to one side',
      'Push back to center, then alternate sides',
    ],
    isDefault: T,
  },
  {
    name: 'Explosive Push-Up',
    description: 'Plyometric push-up where hands leave the floor at the top',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [TRICEPS, FRONT_DELTS],
    equipmentType: BW,
    movementPattern: PUSH,
    difficultyLevel: ADV,
    exerciseType: MEDIUM,
    metricType: REPS,
    instructions: [
      'Start in standard push-up position',
      'Lower chest to the floor with control',
      'Explosively push up so hands leave the floor',
      'Land with soft elbows and immediately descend for the next rep',
      'Can progress to clapping push-ups or chest-to-floor variations',
    ],
    isDefault: T,
  },
  {
    name: 'Medicine Ball Chest Throw',
    description: 'Explosive chest pass using a medicine ball against a wall or with a partner',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [TRICEPS, FRONT_DELTS],
    equipmentType: BW,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: REPS,
    instructions: [
      'Stand facing a wall or partner holding a medicine ball at chest',
      'Bend knees slightly for a stable base',
      'Explosively throw ball from chest with both hands',
      'Catch the rebound and immediately reload for the next rep',
    ],
    isDefault: T,
  },
  {
    name: 'Landmine Press',
    description: 'Single or double-arm press using a landmine attachment for chest and shoulders',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [FRONT_DELTS, TRICEPS],
    equipmentType: B,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Anchor a barbell in a landmine attachment or corner',
      'Kneel or stand facing the bar, holding the end with both hands at chest',
      'Press the bar up and forward until arms are nearly extended',
      'Lower with control back to chest',
      'The arc of movement naturally targets the upper chest',
    ],
    isDefault: T,
  },
  {
    name: 'Incline Machine Press',
    description: 'Machine chest press on an incline targeting the upper chest',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [FRONT_DELTS, TRICEPS],
    equipmentType: M,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Adjust seat so handles align with upper chest on the incline machine',
      'Grip handles and plant feet firmly',
      'Press handles up and forward until arms are nearly extended',
      'Return with control for a full chest stretch',
    ],
    isDefault: T,
  },
  {
    name: 'Decline Machine Press',
    description: 'Machine chest press on a decline targeting the lower chest',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [TRICEPS, FRONT_DELTS],
    equipmentType: M,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Adjust seat on decline machine so handles align with lower chest',
      'Grip handles and press forward and downward',
      'Extend arms until nearly locked out',
      'Return with control for a full stretch',
    ],
    isDefault: T,
  },
  {
    name: 'Chest Dips',
    description: 'Dip variation leaning forward to emphasize the chest over the triceps',
    primaryMuscleGroup: CHEST,
    secondaryMuscleGroups: [TRICEPS, FRONT_DELTS],
    equipmentType: BW,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: REPS,
    instructions: [
      'Grip parallel bars and support your body with arms extended',
      'Lean your torso forward at roughly 30–45 degrees',
      'Lower your body by bending your elbows until a deep chest stretch',
      'Push back up, maintaining the forward lean throughout',
      'Leaning forward shifts emphasis from triceps to chest',
    ],
    isDefault: T,
  },
]

// ============================================================================
// BACK — HORIZONTAL ROWS
// ============================================================================

const backRowExercises: ExerciseSeed[] = [
  {
    name: 'Wide Grip Seated Row',
    description: 'Seated cable row with a wide grip targeting outer upper back and rear delts',
    primaryMuscleGroup: UPPER_BACK,
    secondaryMuscleGroups: [REAR_DELTS, BICEPS],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Attach a wide bar to the low cable pulley',
      'Sit with feet on the platform and grip bar at shoulder-width or wider',
      'Pull bar to lower chest, driving elbows back and wide',
      'Squeeze shoulder blades together at the top',
      'Return to starting position with control',
    ],
    isDefault: T,
  },
  {
    name: 'Close Grip Seated Row',
    description: 'Seated cable row with a close neutral grip emphasizing the middle back',
    primaryMuscleGroup: UPPER_BACK,
    secondaryMuscleGroups: [BICEPS, LATS],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Attach a close neutral-grip handle to the low cable pulley',
      'Sit with feet on the platform and grip the handle',
      'Pull handle into your torso, driving elbows straight back',
      'Squeeze the middle back at the peak contraction',
      'Extend arms fully before the next rep',
    ],
    isDefault: T,
  },
  {
    name: 'Chest Supported Row',
    description: 'Dumbbell or barbell row with chest supported to eliminate lower back involvement',
    primaryMuscleGroup: UPPER_BACK,
    secondaryMuscleGroups: [REAR_DELTS, BICEPS],
    equipmentType: DB,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Set an incline bench to 45 degrees and lie chest-down against it',
      'Hold dumbbells hanging straight down below the bench',
      'Row dumbbells up toward hips, driving elbows back',
      'Squeeze shoulder blades at the top, then lower with control',
      'Chest support eliminates momentum and lower back fatigue',
    ],
    isDefault: T,
  },
  {
    name: 'Underhand Barbell Row',
    description: 'Barbell row with a supinated grip targeting the lats and lower traps',
    primaryMuscleGroup: UPPER_BACK,
    secondaryMuscleGroups: [LATS, BICEPS],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Hinge at hips to about 45 degrees with knees slightly bent',
      'Grip barbell with an underhand (supinated) grip at shoulder-width',
      'Row bar into lower abdomen, keeping elbows tucked close to body',
      'Squeeze lats at the top, then lower with control',
      'The underhand grip increases bicep involvement and lat stretch',
    ],
    isDefault: T,
  },
  {
    name: 'T-Bar Row',
    description: 'Compound rowing movement using a T-bar station or landmine for back thickness',
    primaryMuscleGroup: UPPER_BACK,
    secondaryMuscleGroups: [LATS, BICEPS, LOWER_BACK],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Straddle the barbell anchored at one end',
      'Grip the handle or V-bar attachment near the plates',
      'Hinge at hips with a flat back, arms extended',
      'Row the weight toward your chest, driving elbows back',
      'Squeeze upper back at the top and lower with control',
    ],
    isDefault: T,
  },
  {
    name: 'Machine Row',
    description: 'Horizontal rowing using a dedicated machine for back development',
    primaryMuscleGroup: UPPER_BACK,
    secondaryMuscleGroups: [BICEPS, LATS],
    equipmentType: M,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Adjust chest pad and seat so handles are at mid-chest height',
      'Grip handles and brace chest against the pad',
      'Row handles toward your torso, driving elbows back',
      'Squeeze shoulder blades together at peak contraction',
      'Return to full arm extension before the next rep',
    ],
    isDefault: T,
  },
  {
    name: 'Meadows Row',
    description: 'Single-arm landmine row variation for lat and upper back development',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [UPPER_BACK, BICEPS],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Stand perpendicular to the end of a landmine barbell',
      'Hinge forward with a flat back, grip the end of the bar with the far hand',
      'Row the bar up toward your hip, driving elbow back and up',
      'Squeeze the lat at the top, then lower under control',
      'Keep hips square and use a staggered stance for balance',
    ],
    isDefault: T,
  },
  {
    name: 'Inverted Row',
    description: 'Bodyweight horizontal row under a bar or suspension trainer',
    primaryMuscleGroup: UPPER_BACK,
    secondaryMuscleGroups: [BICEPS, REAR_DELTS],
    equipmentType: BW,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: REPS,
    instructions: [
      'Set a barbell in a rack at waist height or use rings/TRX',
      'Lie underneath with straight body, gripping bar with overhand grip',
      'Pull chest up to the bar, keeping body rigid',
      'Lower with control until arms are fully extended',
      'Elevate feet on a bench to increase difficulty',
    ],
    isDefault: T,
  },
  {
    name: 'Ring Row',
    description: 'Bodyweight row using gymnastic rings for increased range of motion',
    primaryMuscleGroup: UPPER_BACK,
    secondaryMuscleGroups: [BICEPS, REAR_DELTS],
    equipmentType: TRX,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: REPS,
    instructions: [
      'Set rings at waist height',
      'Grip rings and lean back with straight body, arms extended',
      'Pull chest up to ring height, turning palms inward at top',
      'Lower with control until arms fully extend',
      'Walk feet forward to increase difficulty',
    ],
    isDefault: T,
  },
  {
    name: 'Rope Face Pull',
    description: 'Cable face pull using a rope attachment for rear delts and upper back',
    primaryMuscleGroup: REAR_DELTS,
    secondaryMuscleGroups: [UPPER_BACK, TRAPS],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Attach a rope to a cable set at upper chest or face height',
      'Grip the rope ends with both hands, palms facing inward',
      'Pull the rope toward your face, separating hands at the end',
      'Drive elbows back and up to maximize rear delt contraction',
      'Return with control and repeat',
    ],
    isDefault: T,
  },
  {
    name: 'Chest Supported T-Bar Row',
    description: 'T-bar row performed with chest on a pad to isolate the back',
    primaryMuscleGroup: UPPER_BACK,
    secondaryMuscleGroups: [LATS, BICEPS],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Lie chest-down on the T-bar row pad with legs on the platform',
      'Grip the handles below with arms extended',
      'Row the weight up toward your chest, driving elbows back',
      'Squeeze shoulder blades together at the top',
      'Lower with control to full arm extension',
    ],
    isDefault: T,
  },
  {
    name: 'Pendlay Row',
    description: 'Strict barbell row from the floor to the chest with a horizontal torso',
    primaryMuscleGroup: UPPER_BACK,
    secondaryMuscleGroups: [LATS, BICEPS, LOWER_BACK],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: ADV,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Set the bar on the floor; hinge to a near-horizontal torso position',
      'Grip bar at shoulder-width with an overhand grip',
      'Explosively row the bar to the lower chest in one movement',
      'Lower the bar completely to the floor between reps',
      'Strict reset each rep eliminates momentum for pure back strength',
    ],
    isDefault: T,
  },
  {
    name: 'Kroc Row',
    description: 'Heavy single-arm dumbbell row with controlled body English for maximum loading',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [UPPER_BACK, BICEPS, FOREARMS],
    equipmentType: DB,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Place one hand on a bench for support in a row position',
      'Hold a heavy dumbbell in the free hand at full arm extension',
      'Row the dumbbell to hip level, allowing slight torso rotation',
      'Lower with control and repeat for high reps',
      'Use heavier weight than standard rows with controlled momentum',
    ],
    isDefault: T,
  },
  {
    name: 'Landmine Row',
    description: 'Bent-over row using a landmine attachment for a natural arc of motion',
    primaryMuscleGroup: UPPER_BACK,
    secondaryMuscleGroups: [LATS, BICEPS],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Anchor one end of the barbell in a landmine',
      'Hinge forward and grip the elevated end of the bar',
      'Row the bar to your lower chest or hip, driving elbow back',
      'Squeeze the back at peak contraction, then lower with control',
    ],
    isDefault: T,
  },
  {
    name: 'Seal Row',
    description: 'Prone barbell row on an elevated bench eliminating all body momentum',
    primaryMuscleGroup: UPPER_BACK,
    secondaryMuscleGroups: [LATS, BICEPS, REAR_DELTS],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Elevate a flat bench on boxes or safeties high enough for barbell clearance',
      'Lie chest-down on the bench with arms hanging toward the barbell below',
      'Row the barbell up to the bench, driving elbows back',
      'Squeeze the upper back at the top, then lower fully',
      'The prone position eliminates all lower back involvement',
    ],
    isDefault: T,
  },
  {
    name: 'Wide Grip Machine Row',
    description: 'Machine row with a wide grip to target the outer upper back and rear delts',
    primaryMuscleGroup: UPPER_BACK,
    secondaryMuscleGroups: [REAR_DELTS],
    equipmentType: M,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Adjust the chest pad and select a wide bar attachment',
      'Grip bar wide with palms facing down or forward',
      'Row bar toward lower chest, driving elbows out wide',
      'Squeeze upper back and rear delts at peak contraction',
    ],
    isDefault: T,
  },
  {
    name: 'Neutral Grip Machine Row',
    description: 'Machine row with a neutral (palms facing each other) grip',
    primaryMuscleGroup: UPPER_BACK,
    secondaryMuscleGroups: [BICEPS, LATS],
    equipmentType: M,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Select a neutral-grip attachment on the row machine',
      'Adjust chest pad and sit with arms extended',
      'Row handles toward your torso with elbows tucked',
      'Squeeze the back at peak contraction, extend fully to start',
    ],
    isDefault: T,
  },
  {
    name: 'High Cable Row',
    description: 'Cable row with the pulley set high, targeting the upper back and rear delts',
    primaryMuscleGroup: UPPER_BACK,
    secondaryMuscleGroups: [REAR_DELTS, BICEPS],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Set cable pulley to head height',
      'Stand or sit facing the cable, grip a bar or rope',
      'Row the attachment to your upper chest, driving elbows back and down',
      'Squeeze upper back at peak contraction',
      'Return with control to full arm extension',
    ],
    isDefault: T,
  },
  {
    name: 'Single Arm Cable Row',
    description: 'Unilateral cable row allowing greater range of motion and core engagement',
    primaryMuscleGroup: UPPER_BACK,
    secondaryMuscleGroups: [LATS, BICEPS, CORE],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Attach a single handle to the low pulley',
      'Sit or stand facing the cable with one hand on the handle',
      'Row the handle to your hip, rotating torso slightly',
      'Squeeze the lat at peak contraction',
      'Return fully extended before the next rep, then switch sides',
    ],
    isDefault: T,
  },
  {
    name: 'Resistance Band Row',
    description: 'Horizontal row using a resistance band anchored to a stable object',
    primaryMuscleGroup: UPPER_BACK,
    secondaryMuscleGroups: [BICEPS, REAR_DELTS],
    equipmentType: RB,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: REPS,
    instructions: [
      'Anchor a resistance band to a stable object at chest height',
      'Grip both ends and step back to create tension',
      'Row handles to your torso, driving elbows back',
      'Squeeze shoulder blades together at the top',
      'Return with control to full arm extension',
    ],
    isDefault: T,
  },
  {
    name: 'Reverse Grip Cable Row',
    description: 'Seated cable row with a supinated grip to target the lower lats',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [UPPER_BACK, BICEPS],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Attach a straight bar to the low cable pulley',
      'Sit with feet on platform and grip bar with underhand (supinated) grip',
      'Row bar to lower abdomen, keeping elbows close to your body',
      'Squeeze lats at the top, then return with control',
    ],
    isDefault: T,
  },
  {
    name: 'Incline Bench Rear Delt Row',
    description: 'Dumbbell row lying face-down on an incline bench to isolate rear delts',
    primaryMuscleGroup: REAR_DELTS,
    secondaryMuscleGroups: [UPPER_BACK],
    equipmentType: DB,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Set bench to 30–45 degree incline and lie chest-down',
      'Hold dumbbells hanging straight below',
      'Row dumbbells up and out wide, leading with elbows',
      'Focus on squeezing the rear delts at the top',
      'Lower under control and repeat',
    ],
    isDefault: T,
  },
  {
    name: 'Batwing Row',
    description: 'Isometric hold dumbbell row with both arms simultaneously for upper back',
    primaryMuscleGroup: UPPER_BACK,
    secondaryMuscleGroups: [REAR_DELTS, BICEPS],
    equipmentType: DB,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Set an incline bench to 45 degrees and lie chest-down',
      'Row both dumbbells simultaneously to your sides at 90-degree elbow angle',
      'Hold at the top for 2–3 seconds before lowering',
      'The isometric hold targets rhomboids and mid-traps intensely',
    ],
    isDefault: T,
  },
  {
    name: 'Suspension Trainer Row',
    description: 'Bodyweight row using TRX or suspension trainer straps',
    primaryMuscleGroup: UPPER_BACK,
    secondaryMuscleGroups: [LATS, BICEPS, CORE],
    equipmentType: TRX,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: REPS,
    instructions: [
      'Set TRX handles at chest height',
      'Lean back gripping handles with body at an angle',
      'Pull chest to hands, keeping body rigid',
      'Squeeze shoulder blades together at the top',
      'Lower with control and walk feet in to increase difficulty',
    ],
    isDefault: T,
  },
  {
    name: 'Crossbody Cable Row',
    description: 'Cable row pulling across the body to target the outer lat',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [UPPER_BACK],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Set a single cable at about hip height',
      'Stand sideways and reach across to grip with the far hand',
      'Row handle back across your body to the hip',
      'Focus on feeling the lat contract, then return with control',
      'Switch sides after completing all reps',
    ],
    isDefault: T,
  },
  {
    name: 'Plate Row',
    description: 'Bent-over row holding a weight plate for a unique hand position',
    primaryMuscleGroup: UPPER_BACK,
    secondaryMuscleGroups: [BICEPS],
    equipmentType: BW,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: REPS,
    instructions: [
      'Hinge forward with a flat back, holding a weight plate with both hands',
      'Let arms hang straight down from shoulders',
      'Row the plate up to lower chest, driving elbows back',
      'Squeeze shoulder blades at the top, then lower with control',
    ],
    isDefault: T,
  },
]

// ============================================================================
// BACK — LAT / VERTICAL PULL
// ============================================================================

const latExercises: ExerciseSeed[] = [
  {
    name: 'Wide Grip Pull-Up',
    description: 'Pull-up with hands wider than shoulder-width for increased lat stretch',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [BICEPS, UPPER_BACK],
    equipmentType: BW,
    movementPattern: PULL,
    difficultyLevel: ADV,
    exerciseType: LARGE,
    metricType: REPS,
    instructions: [
      'Grip the bar wider than shoulder-width with an overhand grip',
      'Hang at full extension with shoulder blades depressed',
      'Pull body up until chin clears the bar, driving elbows down and back',
      'Lower with control to full extension',
    ],
    isDefault: T,
  },
  {
    name: 'Neutral Grip Pull-Up',
    description: 'Pull-up with palms facing each other for reduced shoulder stress',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [BICEPS, UPPER_BACK],
    equipmentType: BW,
    movementPattern: PULL,
    difficultyLevel: ADV,
    exerciseType: LARGE,
    metricType: REPS,
    instructions: [
      'Grip a neutral-grip bar or handles with palms facing each other',
      'Hang with arms fully extended',
      'Pull body up until chin or chest reaches the bar',
      'Lower with control to full extension',
    ],
    isDefault: T,
  },
  {
    name: 'Chin-Up',
    description: 'Underhand grip pull-up with greater bicep activation',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [BICEPS, UPPER_BACK],
    equipmentType: BW,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: LARGE,
    metricType: REPS,
    instructions: [
      'Grip the bar at shoulder-width with an underhand (supinated) grip',
      'Hang at full arm extension',
      'Pull body up until chin clears the bar',
      'Lower with control back to full extension',
      'Supinated grip increases bicep contribution',
    ],
    isDefault: T,
  },
  {
    name: 'Weighted Pull-Up',
    description: 'Pull-up with additional weight for increased strength and muscle gain',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [BICEPS, UPPER_BACK],
    equipmentType: BW,
    movementPattern: PULL,
    difficultyLevel: ADV,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Attach a weight belt with plates or hold a dumbbell between feet',
      'Grip bar at shoulder-width with overhand grip',
      'Pull body up until chin clears the bar',
      'Lower with full control to complete extension',
    ],
    isDefault: T,
  },
  {
    name: 'Assisted Pull-Up',
    description: 'Machine-assisted pull-up for those building the strength for unassisted reps',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [BICEPS, UPPER_BACK],
    equipmentType: M,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: LARGE,
    metricType: CWR,
    instructions: [
      'Set the counterweight to provide the desired assistance',
      'Kneel or stand on the platform and grip the bar',
      'Pull body up until chin clears the bar',
      'Lower with control to full extension',
      'Reduce counterweight as strength improves',
    ],
    isDefault: T,
  },
  {
    name: 'Wide Grip Lat Pulldown',
    description: 'Lat pulldown with a wide grip for greater lat stretch and width',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [BICEPS, UPPER_BACK],
    equipmentType: M,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Grip the lat bar wider than shoulder-width',
      'Sit with thighs secured under the pad, slight lean back',
      'Pull bar down to upper chest, driving elbows down and back',
      'Squeeze lats at the bottom, then extend arms fully upward',
    ],
    isDefault: T,
  },
  {
    name: 'Reverse Grip Lat Pulldown',
    description: 'Lat pulldown with a supinated grip for increased bicep engagement',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [BICEPS, UPPER_BACK],
    equipmentType: M,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Grip the bar at shoulder-width with an underhand (supinated) grip',
      'Sit with thighs secured and slight lean back',
      'Pull bar down to upper chest, elbows tracking close to body',
      'Squeeze lats at the bottom, return to full extension',
    ],
    isDefault: T,
  },
  {
    name: 'Close Grip Lat Pulldown',
    description: 'Lat pulldown with a close neutral grip for lat thickness',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [BICEPS, UPPER_BACK],
    equipmentType: M,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Attach a close neutral-grip handle to the pulldown station',
      'Sit with thighs secured, grip handle with palms facing each other',
      'Pull handle to upper chest, elbows driving straight down',
      'Squeeze lats at the bottom and return to full extension',
    ],
    isDefault: T,
  },
  {
    name: 'Single Arm Lat Pulldown',
    description: 'Unilateral lat pulldown to address side-to-side imbalances',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [BICEPS],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Attach a single handle to the high pulley',
      'Sit or kneel facing the cable with one hand gripping the handle',
      'Pull handle down toward shoulder, keeping elbow tracking back',
      'Squeeze lat at the bottom, return with control, then switch sides',
    ],
    isDefault: T,
  },
  {
    name: 'Straight Arm Pulldown',
    description: 'Lat isolation exercise keeping arms straight throughout the movement',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Attach a bar or rope to the high cable pulley',
      'Stand facing the cable and grip the attachment with arms extended overhead',
      'Keeping arms straight, pull the attachment down to your thighs',
      'Squeeze lats at the bottom, then raise arms back overhead with control',
    ],
    isDefault: T,
  },
  {
    name: 'Kneeling Lat Pulldown',
    description:
      'Lat pulldown performed kneeling to eliminate leg drive and increase core engagement',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [BICEPS, CORE],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Kneel facing a cable machine with the high pulley',
      'Grip a bar or rope slightly wider than shoulders',
      'Pull the attachment down to your chest, driving elbows back',
      'Squeeze lats at the bottom, return to full arm extension overhead',
    ],
    isDefault: T,
  },
  {
    name: 'Cable Pullover',
    description: 'Lat isolation movement using a cable for constant tension',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Attach a bar or rope to the high pulley',
      'Face away from the cable or lie on a bench below it',
      'With arms extended, pull the attachment over and down to your thighs',
      'Squeeze lats at the bottom, return overhead with control',
    ],
    isDefault: T,
  },
  {
    name: 'Dumbbell Pullover',
    description: 'Classic pullover exercise targeting the lats and serratus anterior',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [CHEST, TRICEPS],
    equipmentType: DB,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Lie perpendicular on a bench with only upper back supported',
      'Hold a dumbbell with both hands above chest, arms slightly bent',
      'Lower the dumbbell behind your head in an arc until lats stretch',
      'Pull the dumbbell back over chest using your lats',
      'Hips should drop below bench level for a full stretch',
    ],
    isDefault: T,
  },
  {
    name: 'Barbell Pullover',
    description: 'Pullover using a barbell for heavier loading across lats and chest',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [CHEST, TRICEPS],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Lie on a flat bench holding a barbell above chest with arms slightly bent',
      'Lower the barbell behind your head in a controlled arc',
      'Feel the lat and chest stretch at the bottom',
      'Pull bar back over chest using lats and chest',
      'Use a narrow grip and lighter weight than dumbbell variation',
    ],
    isDefault: T,
  },
  {
    name: 'Machine Pullover',
    description: 'Lat pullover using a dedicated machine for isolated lat training',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [CHEST],
    equipmentType: M,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Adjust seat so shoulders align with the machine pivot point',
      'Place elbows on pads with arms extended overhead',
      'Drive elbows down and forward, contracting the lats',
      'Squeeze at the bottom, then return with control to starting position',
    ],
    isDefault: T,
  },
  {
    name: 'Resistance Band Pulldown',
    description: 'Lat pulldown using a resistance band for home or travel workouts',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [BICEPS],
    equipmentType: RB,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: REPS,
    instructions: [
      'Anchor a resistance band overhead to a pull-up bar or door frame',
      'Kneel facing the anchor and grip the band',
      'Pull band down to chest, driving elbows back and down',
      'Squeeze lats at the bottom, return to full extension',
    ],
    isDefault: T,
  },
  {
    name: 'Archer Pull-Up',
    description: 'Unilateral pull-up variation shifting load to one arm for advanced strength',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [BICEPS, CORE],
    equipmentType: BW,
    movementPattern: PULL,
    difficultyLevel: ADV,
    exerciseType: MEDIUM,
    metricType: REPS,
    instructions: [
      'Grip a wide bar with one overhand and one neutral or underhand grip',
      'Pull up toward the overhand hand while extending the other arm straight',
      'The extended arm provides minimal assistance while the pulling arm works harder',
      'Lower with control and alternate sides',
    ],
    isDefault: T,
  },
  {
    name: 'Commando Pull-Up',
    description: 'Pull-up on a single bar with both hands facing each other',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [BICEPS, CORE],
    equipmentType: BW,
    movementPattern: PULL,
    difficultyLevel: ADV,
    exerciseType: MEDIUM,
    metricType: REPS,
    instructions: [
      'Face the pull-up bar and grip it with both hands facing each other (inline)',
      'Hang and pull your head up to one side of the bar',
      'Lower with control, then pull to the other side on the next rep',
      'Alternate sides each rep',
    ],
    isDefault: T,
  },
  {
    name: 'Mixed Grip Pull-Up',
    description: 'Pull-up with one overhand and one underhand grip for varied muscle activation',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [BICEPS, UPPER_BACK],
    equipmentType: BW,
    movementPattern: PULL,
    difficultyLevel: ADV,
    exerciseType: LARGE,
    metricType: REPS,
    instructions: [
      'Grip bar with one hand overhand and one hand underhand',
      'Hang at full extension and pull body up until chin clears the bar',
      'Lower with control to full extension',
      'Alternate grip sides each set',
    ],
    isDefault: T,
  },
  {
    name: 'Isometric Pull-Up Hold',
    description: 'Static hold at the top of the pull-up position to build grip and lat strength',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [BICEPS, FOREARMS],
    equipmentType: BW,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: STABILITY,
    metricType: DUR,
    instructions: [
      'Pull yourself to the top of the pull-up position (chin over bar)',
      'Hold this position with elbows bent and chin above bar',
      'Maintain tension in lats and biceps throughout',
      'Lower with control after the target hold time',
    ],
    isDefault: T,
  },
  {
    name: 'Scapular Pull-Up',
    description:
      'Movement targeting the lower traps and serratus by depressing the shoulder blades',
    primaryMuscleGroup: UPPER_BACK,
    secondaryMuscleGroups: [TRAPS],
    equipmentType: BW,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: STABILITY,
    metricType: REPS,
    instructions: [
      'Hang from a pull-up bar with straight arms',
      'Without bending the elbows, depress and retract the shoulder blades',
      'Your body will rise slightly — this is the full range of motion',
      'Slowly allow shoulders to rise back to the dead hang position',
      'Focus on feeling the lower traps and serratus working',
    ],
    isDefault: T,
  },
  {
    name: 'Lat Prayer Pulldown',
    description: 'Kneeling lat pulldown with both arms pulling together in a prayer motion',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Kneel in front of a cable machine with the high pulley set',
      'Attach a rope and grip with both hands in a prayer position',
      'Pull the rope down and forward while hinging at the hips',
      'Stretch fully at the top and squeeze lats at the bottom',
    ],
    isDefault: T,
  },
  {
    name: 'Machine High Row',
    description: 'High row machine exercise targeting the upper back and posterior shoulder',
    primaryMuscleGroup: UPPER_BACK,
    secondaryMuscleGroups: [LATS, REAR_DELTS],
    equipmentType: M,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Adjust the seat on the high row machine to appropriate height',
      'Grip handles with arms extended forward at head height',
      'Pull handles toward your face, driving elbows back wide',
      'Squeeze upper back and rear delts at peak contraction',
      'Return to full arm extension with control',
    ],
    isDefault: T,
  },
  {
    name: 'Single Arm Machine Pulldown',
    description: 'Unilateral lat pulldown on a machine to address muscle imbalances',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [BICEPS],
    equipmentType: M,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Attach a single handle to the pulldown station',
      'Sit sideways or facing forward and grip with one hand',
      'Pull handle down to shoulder, driving elbow toward your hip',
      'Squeeze lat at the bottom, return fully, then switch arms',
    ],
    isDefault: T,
  },
  {
    name: 'Supinated Lat Pulldown',
    description: 'Lat pulldown with a close underhand grip for peak lat contraction',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [BICEPS],
    equipmentType: M,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Grip the straight bar at shoulder-width with palms facing you',
      'Sit with thighs secured and lean back slightly',
      'Pull bar to upper chest, driving elbows down',
      'Hold the contraction momentarily, then return with control',
    ],
    isDefault: T,
  },
  {
    name: 'Close Neutral Pulldown',
    description: 'Lat pulldown with a close neutral grip attachment',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [BICEPS, UPPER_BACK],
    equipmentType: M,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Attach a close neutral-grip handle to the lat pulldown machine',
      'Grip with palms facing each other and sit with thighs secured',
      'Pull the handle to upper chest, elbows tracking downward',
      'Return to full arm extension overhead with control',
    ],
    isDefault: T,
  },
  {
    name: 'Rope Lat Pulldown',
    description: 'Lat pulldown using a rope attachment for independent hand movement',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [BICEPS],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Attach a rope to the high pulley',
      'Grip rope ends with palms facing each other',
      'Pull rope down and apart toward your chest',
      'Allow independent arm movement for a full range of motion',
      'Return to full extension overhead',
    ],
    isDefault: T,
  },
  {
    name: 'Behind the Neck Pulldown',
    description: 'Lat pulldown with the bar pulled behind the neck — use caution with neck health',
    primaryMuscleGroup: LATS,
    secondaryMuscleGroups: [UPPER_BACK, BICEPS],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: ADV,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Grip a wide lat bar and sit with thighs secured',
      'Lean head slightly forward and pull bar behind the neck to trap level',
      'Drive elbows back and down to contract the lats',
      'Return bar above head with control',
      'Use caution — this exercise can stress the cervical spine',
    ],
    isDefault: T,
  },
]

// ============================================================================
// LOWER BACK / POSTERIOR CHAIN HINGE
// ============================================================================

const lowerBackExercises: ExerciseSeed[] = [
  {
    name: 'Stiff Leg Deadlift',
    description: 'Deadlift variation keeping legs nearly straight to maximize hamstring stretch',
    primaryMuscleGroup: HAMSTRINGS,
    secondaryMuscleGroups: [LOWER_BACK, GLUTES],
    equipmentType: B,
    movementPattern: HINGE,
    difficultyLevel: INT,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Stand with feet hip-width apart, holding bar at hip level',
      'Keep legs nearly straight with a very slight knee bend',
      'Hinge at hips and lower bar along legs, keeping back flat',
      'Lower until a deep hamstring stretch is felt',
      'Drive hips forward to return to standing',
    ],
    isDefault: T,
  },
  {
    name: 'Barbell Good Morning',
    description: 'Hip hinge with bar on the back targeting hamstrings and lower back',
    primaryMuscleGroup: LOWER_BACK,
    secondaryMuscleGroups: [HAMSTRINGS, GLUTES],
    equipmentType: B,
    movementPattern: HINGE,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Set the bar on your upper back as you would for a squat',
      'Stand with feet shoulder-width apart, slight knee bend',
      'Hinge at the hips, lowering torso until nearly parallel to the floor',
      'Keep back flat and chest up throughout',
      'Drive hips forward to return to standing position',
    ],
    isDefault: T,
  },
  {
    name: 'Back Extension',
    description: 'Bodyweight hyperextension exercise for lower back and glutes',
    primaryMuscleGroup: LOWER_BACK,
    secondaryMuscleGroups: [HAMSTRINGS, GLUTES],
    equipmentType: BW,
    movementPattern: HINGE,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: REPS,
    instructions: [
      'Secure feet and position hips on the hyperextension bench pad',
      'Cross arms on chest or extend behind head',
      'Lower torso toward the floor with a controlled descent',
      'Raise torso back to parallel with the floor, squeezing glutes',
      'Avoid hyperextending the lower back at the top',
    ],
    isDefault: T,
  },
  {
    name: 'Weighted Back Extension',
    description: 'Back extension with a weight plate for added resistance',
    primaryMuscleGroup: LOWER_BACK,
    secondaryMuscleGroups: [HAMSTRINGS, GLUTES],
    equipmentType: BW,
    movementPattern: HINGE,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Secure feet and position hips on the hyperextension bench',
      'Hold a weight plate or dumbbell against your chest',
      'Lower torso in a controlled arc toward the floor',
      'Raise torso back to parallel, squeezing glutes at the top',
    ],
    isDefault: T,
  },
  {
    name: 'Reverse Hyperextension',
    description: 'Lower back and glute exercise lifting the legs while torso is fixed',
    primaryMuscleGroup: LOWER_BACK,
    secondaryMuscleGroups: [GLUTES, HAMSTRINGS],
    equipmentType: M,
    movementPattern: HINGE,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Lie face-down on the reverse hyper machine with hips at the edge',
      'Hook feet or ankles into the ankle strap attachment',
      'Swing legs upward by extending the hips and lower back',
      'Hold briefly at the top, then lower with control',
      'Avoid using excessive momentum',
    ],
    isDefault: T,
  },
  {
    name: 'Cable Pull Through',
    description: 'Hip hinge using a cable between the legs to target glutes and hamstrings',
    primaryMuscleGroup: GLUTES,
    secondaryMuscleGroups: [HAMSTRINGS, LOWER_BACK],
    equipmentType: C,
    movementPattern: HINGE,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Set a cable to the lowest position and attach a rope',
      'Face away from the machine, straddle the rope with a wide stance',
      'Grip the rope between legs and hinge forward at the hips',
      'Drive hips forward to return to standing, squeezing glutes at top',
      'Maintain a neutral spine throughout',
    ],
    isDefault: T,
  },
  {
    name: 'Rack Pull',
    description: 'Deadlift variation starting from a rack position at knee height or above',
    primaryMuscleGroup: LOWER_BACK,
    secondaryMuscleGroups: [HAMSTRINGS, GLUTES, TRAPS],
    equipmentType: B,
    movementPattern: HINGE,
    difficultyLevel: INT,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Set barbell in a power rack at knee height or slightly above',
      'Stand over the bar with feet hip-width apart',
      'Grip bar overhand or mixed at shoulder-width',
      'Drive hips forward to stand upright, locking out hips and knees',
      'Lower bar back to the pins with control',
    ],
    isDefault: T,
  },
  {
    name: 'Deficit Deadlift',
    description: 'Deadlift performed standing on a raised platform to increase range of motion',
    primaryMuscleGroup: LOWER_BACK,
    secondaryMuscleGroups: [HAMSTRINGS, GLUTES, QUADS],
    equipmentType: B,
    movementPattern: HINGE,
    difficultyLevel: ADV,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Stand on a 1–4 inch platform with barbell on the floor',
      'The elevated stance requires a deeper starting position',
      'Grip bar at shoulder-width and brace with flat back',
      'Drive through legs and extend hips to stand',
      'Lower bar to floor with control for each rep',
    ],
    isDefault: T,
  },
  {
    name: 'Snatch Grip Deadlift',
    description: 'Deadlift with an extra-wide snatch grip for upper back and trap development',
    primaryMuscleGroup: LOWER_BACK,
    secondaryMuscleGroups: [HAMSTRINGS, GLUTES, UPPER_BACK, TRAPS],
    equipmentType: B,
    movementPattern: HINGE,
    difficultyLevel: ADV,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Grip the bar with a very wide grip (snatch width, just inside collar)',
      'Start with hips lower than a conventional deadlift due to wider grip',
      'Drive through legs and extend hips to stand',
      'The wide grip increases upper back and trap activation',
      'Lower bar with control for each rep',
    ],
    isDefault: T,
  },
  {
    name: 'Trap Bar Deadlift',
    description: 'Deadlift using a hex/trap bar for reduced lower back stress',
    primaryMuscleGroup: LOWER_BACK,
    secondaryMuscleGroups: [QUADS, HAMSTRINGS, GLUTES],
    equipmentType: B,
    movementPattern: HINGE,
    difficultyLevel: INT,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Stand inside the trap bar with feet hip-width apart',
      'Grip the handles at hip level with a neutral grip',
      'Keep chest up and back flat, push through heels to stand',
      'Extend hips and knees simultaneously to lockout',
      'Lower bar with control back to the floor',
    ],
    isDefault: T,
  },
  {
    name: 'Kettlebell Deadlift',
    description: 'Deadlift pattern using a kettlebell, ideal for beginners learning the hinge',
    primaryMuscleGroup: LOWER_BACK,
    secondaryMuscleGroups: [HAMSTRINGS, GLUTES],
    equipmentType: KB,
    movementPattern: HINGE,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Stand over a kettlebell with feet shoulder-width apart',
      'Hinge at hips and grip the kettlebell handle',
      'Keep back flat and drive through heels to stand',
      'Squeeze glutes at lockout',
      'Lower kettlebell with control by hinging at the hips',
    ],
    isDefault: T,
  },
  {
    name: 'Jefferson Deadlift',
    description: 'Straddle deadlift with one foot on each side of the bar for hip mobility',
    primaryMuscleGroup: LOWER_BACK,
    secondaryMuscleGroups: [QUADS, HAMSTRINGS, GLUTES, CORE],
    equipmentType: B,
    movementPattern: HINGE,
    difficultyLevel: ADV,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Straddle the barbell with one foot in front and one behind',
      'Grip bar with one hand in front and one behind (mixed stance)',
      'Keep chest up and back flat',
      'Drive through both feet to stand, extending hips and knees',
      'Lower with control, alternate foot and grip positions each set',
    ],
    isDefault: T,
  },
  {
    name: 'Suitcase Deadlift',
    description: 'Single-arm deadlift holding the bar at your side like a suitcase',
    primaryMuscleGroup: LOWER_BACK,
    secondaryMuscleGroups: [CORE, HAMSTRINGS, GLUTES],
    equipmentType: B,
    movementPattern: HINGE,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Stand beside the barbell and grip it at center with one hand',
      'Keep the bar parallel to your body throughout the lift',
      'Hinge at hips, keeping back neutral and core tight to resist lateral tilt',
      'Drive through feet to stand, maintaining upright posture',
      'Lower with control, then switch sides',
    ],
    isDefault: T,
  },
  {
    name: 'Resistance Band Good Morning',
    description: 'Hip hinge using a resistance band for a lower back warm-up or accessory movement',
    primaryMuscleGroup: LOWER_BACK,
    secondaryMuscleGroups: [HAMSTRINGS],
    equipmentType: RB,
    movementPattern: HINGE,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: REPS,
    instructions: [
      'Loop a resistance band behind your neck and under both feet',
      'Stand with feet shoulder-width apart and the band creating tension',
      'Hinge at hips lowering torso until nearly parallel to the floor',
      'Drive hips forward to return to standing',
    ],
    isDefault: T,
  },
  {
    name: 'Glute Ham Raise',
    description: 'Advanced bodyweight exercise for hamstrings and glutes using a GHD bench',
    primaryMuscleGroup: HAMSTRINGS,
    secondaryMuscleGroups: [GLUTES, LOWER_BACK],
    equipmentType: M,
    movementPattern: HINGE,
    difficultyLevel: ADV,
    exerciseType: MEDIUM,
    metricType: REPS,
    instructions: [
      'Secure feet in the GHD machine foot pads with knees on the knee pad',
      'Lower body from vertical until torso is parallel to the floor',
      'Curl body back up by contracting hamstrings and glutes',
      'Keep core tight and hips extended throughout',
    ],
    isDefault: T,
  },
  {
    name: 'Isometric Back Extension Hold',
    description: 'Static hold in the raised position of a back extension for lower back endurance',
    primaryMuscleGroup: LOWER_BACK,
    secondaryMuscleGroups: [HAMSTRINGS, GLUTES],
    equipmentType: BW,
    movementPattern: HINGE,
    difficultyLevel: BEG,
    exerciseType: STABILITY,
    metricType: DUR,
    instructions: [
      'Position on a back extension bench with hips at the edge',
      'Raise torso to parallel with the floor',
      'Hold this position with a neutral spine',
      'Focus on lower back and glute tension throughout the hold',
    ],
    isDefault: T,
  },
  {
    name: 'Hip Hinge Drill',
    description: 'Bodyweight drill to reinforce proper hip hinge mechanics',
    primaryMuscleGroup: LOWER_BACK,
    secondaryMuscleGroups: [HAMSTRINGS, GLUTES],
    equipmentType: BW,
    movementPattern: HINGE,
    difficultyLevel: BEG,
    exerciseType: STABILITY,
    metricType: REPS,
    instructions: [
      'Stand about 1 foot from a wall, feet hip-width apart',
      'Push your hips back toward the wall while maintaining a flat back',
      'Lower until you feel hamstring tension, keeping chest tall',
      'Drive hips forward to return to standing position',
      'Use a dowel rod along your spine for feedback on form',
    ],
    isDefault: T,
  },
]

// ============================================================================
// TRAPS
// ============================================================================

const trapExercises: ExerciseSeed[] = [
  {
    name: 'Barbell Shrug',
    description: 'Classic barbell shrug for upper trap development',
    primaryMuscleGroup: TRAPS,
    secondaryMuscleGroups: [],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Hold barbell in front of body with arms extended',
      'Shrug shoulders straight up toward ears',
      'Hold briefly at the top of the movement',
      'Lower shoulders with control',
      'Avoid rolling shoulders — move straight up and down',
    ],
    isDefault: T,
  },
  {
    name: 'Dumbbell Shrug',
    description: 'Dumbbell shrug for upper trap development with neutral grip',
    primaryMuscleGroup: TRAPS,
    secondaryMuscleGroups: [],
    equipmentType: DB,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Stand holding dumbbells at sides with neutral grip',
      'Shrug shoulders straight up toward ears',
      'Hold briefly at the top for peak contraction',
      'Lower with control and repeat',
    ],
    isDefault: T,
  },
  {
    name: 'Smith Machine Shrug',
    description: 'Shrug performed on a Smith machine for stable path of motion',
    primaryMuscleGroup: TRAPS,
    secondaryMuscleGroups: [],
    equipmentType: M,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Set bar at hip level in Smith machine',
      'Grip bar at shoulder-width and unhook',
      'Shrug shoulders straight up toward ears',
      'Hold briefly, then lower with control',
    ],
    isDefault: T,
  },
  {
    name: 'Trap Bar Shrug',
    description: 'Shrug using a trap bar allowing neutral hand position and heavier loading',
    primaryMuscleGroup: TRAPS,
    secondaryMuscleGroups: [],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Stand inside a loaded trap bar and grip the handles',
      'Stand tall with arms extended and bar cleared',
      'Shrug shoulders straight up toward ears',
      'Hold briefly at the top, then lower with control',
    ],
    isDefault: T,
  },
  {
    name: 'Behind the Back Shrug',
    description: 'Barbell shrug with bar held behind the body to target middle traps',
    primaryMuscleGroup: TRAPS,
    secondaryMuscleGroups: [],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      "Hold barbell behind your body at arm's length",
      'Stand tall with arms extended and shoulders relaxed',
      'Shrug shoulders upward and slightly back',
      'Hold at the top, then lower with control',
    ],
    isDefault: T,
  },
  {
    name: 'Barbell High Pull',
    description: 'Explosive upright row from the floor targeting traps and upper back',
    primaryMuscleGroup: TRAPS,
    secondaryMuscleGroups: [UPPER_BACK, FRONT_DELTS],
    equipmentType: B,
    movementPattern: OLYMPIC,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Stand with barbell at thighs, grip just outside hip-width',
      'Explosively extend hips and rise up onto toes',
      'Pull bar up to chin height, driving elbows high',
      'Lower bar with control back to starting position',
    ],
    isDefault: T,
  },
  {
    name: 'Power Shrug',
    description: 'Heavy explosive shrug using hip extension and leg drive for overloading traps',
    primaryMuscleGroup: TRAPS,
    secondaryMuscleGroups: [UPPER_BACK, LOWER_BACK],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: ADV,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Hold a very heavy barbell at hip level',
      'Slightly dip at the knees',
      'Drive hips forward and use leg drive to help shrug shoulders explosively',
      'Rise onto toes at the top of the movement',
      'Lower with control — primarily a strength overload exercise',
    ],
    isDefault: T,
  },
  {
    name: 'Upright Row',
    description: 'Vertical pull targeting the upper traps and side delts',
    primaryMuscleGroup: TRAPS,
    secondaryMuscleGroups: [SIDE_DELTS, BICEPS, FRONT_DELTS],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Hold barbell in front of body with overhand grip, hands close together',
      'Pull bar straight up to chin height, leading with elbows',
      'Elbows should rise higher than hands throughout',
      'Lower bar with control back to starting position',
    ],
    isDefault: T,
  },
  {
    name: 'Wide Grip Upright Row',
    description: 'Upright row with a wide grip to shift emphasis to the lateral deltoids',
    primaryMuscleGroup: SIDE_DELTS,
    secondaryMuscleGroups: [TRAPS, BICEPS],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Hold barbell with a grip wider than shoulder-width',
      'Pull bar upward toward chin, keeping elbows high',
      'Wide grip limits how high you can pull but increases delt activation',
      'Lower with control back to starting position',
    ],
    isDefault: T,
  },
  {
    name: 'Cable Upright Row',
    description: 'Upright row using a cable for constant tension through the full range',
    primaryMuscleGroup: TRAPS,
    secondaryMuscleGroups: [SIDE_DELTS, BICEPS],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Attach a straight bar or rope to the low cable pulley',
      'Stand facing the machine and grip the attachment',
      'Pull attachment upward to chin height, leading with elbows',
      'Lower with control back to starting position',
    ],
    isDefault: T,
  },
  {
    name: 'Snatch Grip High Pull',
    description:
      'Olympic-style high pull using a wide snatch grip for upper back and trap development',
    primaryMuscleGroup: TRAPS,
    secondaryMuscleGroups: [UPPER_BACK, FRONT_DELTS, LOWER_BACK],
    equipmentType: B,
    movementPattern: OLYMPIC,
    difficultyLevel: ADV,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Set up with a wide snatch grip at the bar',
      'Begin with a conventional deadlift position',
      'Explosively extend hips, knees, and ankles',
      'Pull bar high using shoulders and elbows, reaching shoulder height',
      'Lower under control and reset',
    ],
    isDefault: T,
  },
  {
    name: 'Clean Pull',
    description: 'Pulling portion of the power clean to develop extension power and trap strength',
    primaryMuscleGroup: TRAPS,
    secondaryMuscleGroups: [UPPER_BACK, LOWER_BACK, QUADS],
    equipmentType: B,
    movementPattern: OLYMPIC,
    difficultyLevel: ADV,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Set up in clean pulling position with bar on the floor',
      'Drive explosively through legs, then extend hips and ankles',
      'Shrug aggressively at the top to maximize trap activation',
      'Pull bar to mid-chest height without catching',
      'Lower bar with control and reset',
    ],
    isDefault: T,
  },
  {
    name: 'Hang High Pull',
    description: 'High pull starting from the hang position at mid-thigh',
    primaryMuscleGroup: TRAPS,
    secondaryMuscleGroups: [UPPER_BACK, FRONT_DELTS],
    equipmentType: B,
    movementPattern: OLYMPIC,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Hold barbell at mid-thigh with hips hinged back',
      'Explosively extend hips and rise onto toes',
      'Shrug and pull bar to chin height, elbows driving high',
      'Lower bar back to hang position with control',
    ],
    isDefault: T,
  },
  {
    name: 'Face Pull to Neck',
    description: 'Cable face pull with a higher pull path targeting upper traps and rear delts',
    primaryMuscleGroup: REAR_DELTS,
    secondaryMuscleGroups: [UPPER_BACK, TRAPS],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Set cable slightly above head height and attach a rope',
      'Grip rope and pull toward your neck, separating hands at the end',
      'Drive elbows up and back to contract rear delts and upper traps',
      'Return with control and repeat',
    ],
    isDefault: T,
  },
  {
    name: 'Plate Shrug',
    description: 'Shrug holding a weight plate for a unique grip training element',
    primaryMuscleGroup: TRAPS,
    secondaryMuscleGroups: [FOREARMS],
    equipmentType: BW,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Hold a weight plate with both hands using a pinch grip on the edges',
      'Stand with arms extended downward',
      'Shrug shoulders up toward ears',
      'Hold briefly, then lower with control',
    ],
    isDefault: T,
  },
  {
    name: 'Incline Dumbbell Shrug',
    description: 'Shrug on an incline bench for mid-trap emphasis',
    primaryMuscleGroup: TRAPS,
    secondaryMuscleGroups: [],
    equipmentType: DB,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Lie chest-down on an incline bench set to 45 degrees',
      'Hold dumbbells hanging straight down',
      'Shrug shoulders straight up toward your ears',
      'Hold briefly at the top, then lower with control',
    ],
    isDefault: T,
  },
  {
    name: 'Seated Dumbbell Shrug',
    description: 'Dumbbell shrug performed seated to eliminate leg drive',
    primaryMuscleGroup: TRAPS,
    secondaryMuscleGroups: [],
    equipmentType: DB,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Sit on the end of a bench holding dumbbells at sides',
      'Keep torso upright and back straight',
      'Shrug shoulders straight up toward ears',
      'Hold at the top briefly, then lower with control',
    ],
    isDefault: T,
  },
  {
    name: 'Overhead Shrug',
    description: 'Shrug with arms extended overhead to target the lower and middle traps',
    primaryMuscleGroup: TRAPS,
    secondaryMuscleGroups: [UPPER_BACK],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: ADV,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Hold a barbell overhead in a locked-out position, snatch-width grip',
      'Allow shoulders to shrug upward toward ears',
      'Then actively depress shoulders down and back',
      'This trains the lower traps in a difficult position',
      'Use light weight — shoulder stability is the priority',
    ],
    isDefault: T,
  },
]

// ============================================================================
// Main
// ============================================================================

const BATCH_SIZE = 50

async function main() {
  // console.log('Starting exercise seed v2 (chest, back, lats, lower back, traps)...')

  const existing = await prisma.exercise.findMany({ select: { name: true } })
  const existingNames = new Set(existing.map((e) => e.name))
  // console.log(`Found ${existingNames.size} existing exercises`)

  const allExercises: ExerciseSeed[] = [
    ...chestExercises,
    ...backRowExercises,
    ...latExercises,
    ...lowerBackExercises,
    ...trapExercises,
  ]

  const toCreate = allExercises.filter((e) => !existingNames.has(e.name))
  // console.log(`Will create ${toCreate.length} new exercises (${allExercises.length - toCreate.length} already exist)`)

  // let created = 0
  for (let i = 0; i < toCreate.length; i += BATCH_SIZE) {
    const batch = toCreate.slice(i, i + BATCH_SIZE)
    // const result = await prisma.exercise.createMany({ data: batch })
    await prisma.exercise.createMany({ data: batch })
    // created += result.count
    // console.log(`Batch ${Math.floor(i / BATCH_SIZE) + 1}: inserted ${result.count}`)
  }

  // console.log(`Done! Created ${created} exercises.`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
