/**
 * Exercise Seed Script v2b
 *
 * Adds shoulders, arms, and forearm exercises.
 * Skips any exercises that already exist in the database by name.
 *
 * Run with: npx ts-node prisma/seed-exercises-v2b.ts
 */

import {
  PrismaClient,
  MuscleGroup,
  EquipmentType,
  MovementPattern,
  DifficultyLevel,
  ExerciseType,
  MetricType,
} from '@prisma/client'

const prisma = new PrismaClient()

const B = EquipmentType.BARBELL
const DB = EquipmentType.DUMBBELL
const KB = EquipmentType.KETTLEBELL
const M = EquipmentType.MACHINE
const C = EquipmentType.CABLE
const BW = EquipmentType.BODYWEIGHT
const RB = EquipmentType.RESISTANCE_BAND

const CHEST = MuscleGroup.CHEST
const UPPER_BACK = MuscleGroup.UPPER_BACK
const LATS = MuscleGroup.LATS
const LOWER_BACK = MuscleGroup.LOWER_BACK
const TRAPS = MuscleGroup.TRAPS
const FRONT_DELTS = MuscleGroup.FRONT_DELTS
const SIDE_DELTS = MuscleGroup.SIDE_DELTS
const REAR_DELTS = MuscleGroup.REAR_DELTS
const BICEPS = MuscleGroup.BICEPS
const TRICEPS = MuscleGroup.TRICEPS
const FOREARMS = MuscleGroup.FOREARMS
// const QUADS = MuscleGroup.QUADS
const CORE = MuscleGroup.CORE

const PUSH = MovementPattern.PUSH
const PULL = MovementPattern.PULL
const CARRY = MovementPattern.CARRY
const CORE_PAT = MovementPattern.CORE

const BEG = DifficultyLevel.BEGINNER
const INT = DifficultyLevel.INTERMEDIATE
const ADV = DifficultyLevel.ADVANCED

const SMALL = ExerciseType.SMALL
const MEDIUM = ExerciseType.MEDIUM
const LARGE = ExerciseType.LARGE

const WR = MetricType.WEIGHT_REPS
const REPS = MetricType.REPS
const DUR = MetricType.DURATION

const T = true

type ExerciseSeed = {
  name: string
  description?: string
  primaryMuscleGroup: MuscleGroup
  secondaryMuscleGroups: MuscleGroup[]
  equipmentType: EquipmentType
  movementPattern: MovementPattern
  difficultyLevel: DifficultyLevel
  exerciseType: ExerciseType
  metricType: MetricType
  instructions: string[]
  isDefault: boolean
}

// ============================================================================
// Shoulder Press Exercises
// ============================================================================

const shoulderPressExercises: ExerciseSeed[] = [
  {
    name: 'Seated Barbell Press',
    description: 'Strict seated overhead press with a barbell for maximum shoulder strength',
    primaryMuscleGroup: FRONT_DELTS,
    secondaryMuscleGroups: [SIDE_DELTS, TRICEPS, UPPER_BACK, TRAPS],
    equipmentType: B,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Sit on a bench with back support, feet flat on the floor',
      'Unrack the barbell at chin height with a grip slightly wider than shoulder-width',
      'Press the barbell overhead until arms are fully extended',
      'Lower the bar under control back to chin height',
      'Keep core braced and avoid excessive lumbar extension',
    ],
    isDefault: T,
  },
  {
    name: 'Seated Dumbbell Press',
    description: 'Seated overhead press with dumbbells for balanced shoulder development',
    primaryMuscleGroup: FRONT_DELTS,
    secondaryMuscleGroups: [SIDE_DELTS, TRICEPS],
    equipmentType: DB,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Sit on a bench with back support, dumbbells resting on thighs',
      'Kick dumbbells up to shoulder height, palms facing forward',
      'Press both dumbbells overhead until arms are fully extended',
      'Lower the dumbbells under control back to shoulder level',
      'Keep core engaged throughout the movement',
    ],
    isDefault: T,
  },
  {
    name: 'Arnold Press',
    description: 'Rotational dumbbell press that targets all three deltoid heads',
    primaryMuscleGroup: FRONT_DELTS,
    secondaryMuscleGroups: [SIDE_DELTS, REAR_DELTS, TRICEPS],
    equipmentType: DB,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Sit on a bench, hold dumbbells at shoulder height with palms facing you',
      'Begin pressing upward while rotating wrists outward',
      'By the time arms are fully extended, palms should face forward',
      'Reverse the rotation as you lower the dumbbells back to start',
      'Control the rotation throughout — do not rush the movement',
    ],
    isDefault: T,
  },
  {
    name: 'Smith Machine Shoulder Press',
    description: 'Overhead press on a Smith machine for guided shoulder training',
    primaryMuscleGroup: FRONT_DELTS,
    secondaryMuscleGroups: [SIDE_DELTS, TRICEPS],
    equipmentType: M,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Sit on a bench inside the Smith machine, bar at upper chest height',
      'Grip the bar slightly wider than shoulder-width',
      'Unrack and press the bar overhead until arms are extended',
      'Lower the bar under control back to chin/upper-chest level',
      'Keep back flat against the bench pad throughout',
    ],
    isDefault: T,
  },
  {
    name: 'Machine Shoulder Press',
    description: 'Fixed-path overhead press machine for safe shoulder loading',
    primaryMuscleGroup: FRONT_DELTS,
    secondaryMuscleGroups: [SIDE_DELTS, TRICEPS],
    equipmentType: M,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Adjust seat height so handles align with upper chest',
      'Grip handles with palms facing forward or neutral',
      'Press handles overhead until arms are fully extended',
      'Lower handles back to starting position under control',
      'Keep core engaged and avoid shrugging at the top',
    ],
    isDefault: T,
  },
  {
    name: 'Landmine Shoulder Press',
    description: 'Angled press with a landmine attachment for shoulder-friendly overhead loading',
    primaryMuscleGroup: FRONT_DELTS,
    secondaryMuscleGroups: [TRICEPS, UPPER_BACK, CORE],
    equipmentType: B,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Stand in a staggered stance facing a landmine-anchored barbell',
      'Hold the end of the barbell at shoulder height with both hands',
      'Press the bar up and forward in an arc until arms extend',
      'Lower the bar back to shoulder level under control',
      'Brace the core — the angled path reduces shoulder impingement risk',
    ],
    isDefault: T,
  },
  {
    name: 'Single Arm Landmine Press',
    description: 'Unilateral landmine press that challenges core stability',
    primaryMuscleGroup: FRONT_DELTS,
    secondaryMuscleGroups: [TRICEPS, CORE, SIDE_DELTS],
    equipmentType: B,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Stand in a staggered stance, hold the barbell sleeve with one hand at shoulder height',
      'Press the bar up and forward in an arc to full arm extension',
      'Lower back to shoulder height under control',
      'Keep the torso square — avoid rotating toward the working arm',
      'Complete all reps on one side before switching',
    ],
    isDefault: T,
  },
  {
    name: 'Plate Front Raise',
    description: 'Front raise with a weight plate for anterior deltoid isolation',
    primaryMuscleGroup: FRONT_DELTS,
    secondaryMuscleGroups: [SIDE_DELTS],
    equipmentType: BW,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Stand upright holding a weight plate with both hands at thigh level',
      'Keep a slight bend in the elbows throughout the movement',
      'Raise the plate forward to shoulder height (parallel with floor)',
      'Pause briefly at the top, then lower under control',
      'Avoid swinging the torso — use slow, controlled reps',
    ],
    isDefault: T,
  },
  {
    name: 'Barbell Front Raise',
    description: 'Bilateral front raise with a barbell for anterior deltoid work',
    primaryMuscleGroup: FRONT_DELTS,
    secondaryMuscleGroups: [SIDE_DELTS, UPPER_BACK],
    equipmentType: B,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Stand holding a barbell in front of thighs with an overhand grip',
      'Keep a slight bend in the elbows',
      'Raise the barbell forward until arms are parallel with the floor',
      'Pause at the top, then slowly lower back down',
      'Avoid using momentum — keep the movement strict',
    ],
    isDefault: T,
  },
  {
    name: 'Dumbbell Front Raise',
    description: 'Unilateral or bilateral front raise with dumbbells',
    primaryMuscleGroup: FRONT_DELTS,
    secondaryMuscleGroups: [SIDE_DELTS],
    equipmentType: DB,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Stand holding dumbbells in front of thighs, palms facing down',
      'Raise one or both dumbbells forward to shoulder height',
      'Keep arms nearly straight with a soft elbow bend',
      'Lower under control back to the starting position',
      'Alternate arms or perform both simultaneously',
    ],
    isDefault: T,
  },
  {
    name: 'Cable Front Raise',
    description: 'Cable front raise with constant tension throughout the range of motion',
    primaryMuscleGroup: FRONT_DELTS,
    secondaryMuscleGroups: [SIDE_DELTS],
    equipmentType: C,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Attach a straight bar or single handle to a low cable pulley',
      'Stand facing away from the machine, hold the attachment at thigh level',
      'Raise the handle forward to shoulder height with a slight elbow bend',
      'Lower back under control, maintaining cable tension throughout',
      'Avoid swinging — the cable maintains constant load',
    ],
    isDefault: T,
  },
  {
    name: 'Kettlebell Overhead Press',
    description: 'Single-arm overhead press with a kettlebell for shoulder stability',
    primaryMuscleGroup: FRONT_DELTS,
    secondaryMuscleGroups: [TRICEPS, SIDE_DELTS, CORE],
    equipmentType: KB,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Clean a kettlebell to the rack position — elbow tucked, bell resting on forearm',
      'Brace the core and glutes before pressing',
      'Press the kettlebell straight overhead until arm is fully extended',
      'Lower the kettlebell back to the rack position under control',
      'Keep the wrist stacked over the elbow throughout',
    ],
    isDefault: T,
  },
  {
    name: 'Z Press',
    description: 'Seated floor overhead press that eliminates leg drive and demands core stability',
    primaryMuscleGroup: FRONT_DELTS,
    secondaryMuscleGroups: [TRICEPS, CORE, UPPER_BACK],
    equipmentType: B,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Sit on the floor with legs straight out in front of you, barbell in a rack at chest height',
      'Unrack the bar and hold it at upper chest level with a shoulder-width grip',
      'Press the barbell overhead until arms are fully extended',
      'Lower the bar back to chest level under control',
      'The floor seat removes leg drive, demanding strict shoulder and core engagement',
    ],
    isDefault: T,
  },
]

// ============================================================================
// Lateral Raise Exercises
// ============================================================================

const lateralRaiseExercises: ExerciseSeed[] = [
  {
    name: 'Dumbbell Lateral Raise',
    description: 'Classic lateral raise with dumbbells to isolate the medial deltoid',
    primaryMuscleGroup: SIDE_DELTS,
    secondaryMuscleGroups: [TRAPS, FRONT_DELTS],
    equipmentType: DB,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Stand with dumbbells at your sides, slight bend in elbows',
      'Raise both arms out to the sides to shoulder height',
      'Keep wrists slightly below elbows to maximize side delt activation',
      'Pause at the top, then lower under control',
      'Avoid shrugging — keep traps relaxed throughout',
    ],
    isDefault: T,
  },
  {
    name: 'Seated Lateral Raise',
    description: 'Lateral raise performed seated to reduce momentum',
    primaryMuscleGroup: SIDE_DELTS,
    secondaryMuscleGroups: [TRAPS],
    equipmentType: DB,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Sit on a bench with dumbbells hanging at your sides',
      'Keep a slight bend in the elbows',
      'Raise both arms out to shoulder height',
      'Lower under control — seated position limits body swinging',
      'Focus on squeezing the side delts at the top',
    ],
    isDefault: T,
  },
  {
    name: 'Cable Lateral Raise',
    description: 'Lateral raise with cable for constant tension throughout the movement',
    primaryMuscleGroup: SIDE_DELTS,
    secondaryMuscleGroups: [TRAPS, FRONT_DELTS],
    equipmentType: C,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Stand beside a low cable pulley, handle in the far hand',
      'Let the cable cross in front of your body at a slight angle',
      'Raise the arm out to shoulder height with a slight elbow bend',
      'Lower back under control maintaining cable tension',
      'Perform all reps on one side before switching',
    ],
    isDefault: T,
  },
  {
    name: 'Leaning Cable Lateral Raise',
    description: 'Lateral raise with body lean to increase stretch at the bottom',
    primaryMuscleGroup: SIDE_DELTS,
    secondaryMuscleGroups: [TRAPS],
    equipmentType: C,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Stand beside a cable pulley and hold an upright support with your inner hand',
      'Lean away from the machine, letting the cable arm hang across your body',
      'Raise the cable arm out and up to shoulder height',
      'Lower slowly, feeling the stretch at the bottom',
      'The lean increases range of motion through the bottom',
    ],
    isDefault: T,
  },
  {
    name: 'Machine Lateral Raise',
    description: 'Lateral raise machine for isolated medial delt training',
    primaryMuscleGroup: SIDE_DELTS,
    secondaryMuscleGroups: [TRAPS],
    equipmentType: M,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Adjust the seat so the arm pads align with the elbows',
      'Sit upright and place forearms against the pads',
      'Raise both arms out to shoulder height against the resistance',
      'Lower back slowly under control',
      'Focus on driving with the elbows, not the wrists',
    ],
    isDefault: T,
  },
  {
    name: 'Plate Lateral Raise',
    description: 'Lateral raise using a weight plate held between the hands',
    primaryMuscleGroup: SIDE_DELTS,
    secondaryMuscleGroups: [TRAPS],
    equipmentType: BW,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Stand holding a plate horizontally with both hands at hip level',
      'Raise the plate out to one side to shoulder height (single arm variation)',
      'Or raise both arms simultaneously with one hand on each side of the plate',
      'Lower under control and repeat',
      'The plate grip shifts the load distribution compared to dumbbells',
    ],
    isDefault: T,
  },
  {
    name: 'Incline Lateral Raise',
    description: 'Lateral raise on an incline bench to hit a different delt angle',
    primaryMuscleGroup: SIDE_DELTS,
    secondaryMuscleGroups: [REAR_DELTS],
    equipmentType: DB,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Lie sideways on a 45-degree incline bench with a dumbbell in the top hand',
      'Let the arm hang down toward the floor',
      'Raise the dumbbell upward and out to shoulder height',
      'Lower under control feeling the stretch at the bottom',
      'The incline shifts the load to emphasize the mid-range and stretched position',
    ],
    isDefault: T,
  },
  {
    name: 'Single Arm Machine Lateral Raise',
    description: 'Unilateral lateral raise on a machine for even delt development',
    primaryMuscleGroup: SIDE_DELTS,
    secondaryMuscleGroups: [],
    equipmentType: M,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Set up the machine for single-arm use, adjusting the seat height',
      'Place one forearm or hand on the pad with the arm at your side',
      'Raise the arm out to shoulder height against the resistance',
      'Lower slowly and repeat, then switch sides',
      'Unilateral training helps address side-to-side imbalances',
    ],
    isDefault: T,
  },
  {
    name: 'Resistance Band Lateral Raise',
    description: 'Lateral raise with a resistance band for home or travel training',
    primaryMuscleGroup: SIDE_DELTS,
    secondaryMuscleGroups: [TRAPS],
    equipmentType: RB,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: REPS,
    instructions: [
      'Stand on the middle of a resistance band, feet hip-width apart',
      'Hold one end in each hand at your sides',
      'Raise both arms out to shoulder height against the band resistance',
      'Lower under control',
      'The band increases resistance as you raise higher — adjust band tension as needed',
    ],
    isDefault: T,
  },
  {
    name: 'Behind the Back Cable Lateral Raise',
    description: 'Cable lateral raise with the cable passing behind the body',
    primaryMuscleGroup: SIDE_DELTS,
    secondaryMuscleGroups: [REAR_DELTS],
    equipmentType: C,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Stand with a low cable pulley behind you, hold the handle with your far hand reaching behind your back',
      'Keep a slight elbow bend and raise the arm out to the side',
      'The cable path shifts activation toward the rear portion of the side delt',
      'Lower under control, maintaining cable tension',
      'Keep the torso upright throughout',
    ],
    isDefault: T,
  },
  {
    name: 'Lying Lateral Raise',
    description: 'Lateral raise performed lying on a bench for a unique resistance curve',
    primaryMuscleGroup: SIDE_DELTS,
    secondaryMuscleGroups: [],
    equipmentType: DB,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Lie on your side on a flat bench, holding a dumbbell in the top hand',
      'Allow the arm to hang down across the body',
      'Raise the dumbbell straight up to the ceiling',
      'Lower under control back to the starting position',
      'The lying position provides maximum tension at the top of the movement',
    ],
    isDefault: T,
  },
  {
    name: 'Kettlebell Lateral Raise',
    description: 'Lateral raise with a kettlebell for additional grip challenge',
    primaryMuscleGroup: SIDE_DELTS,
    secondaryMuscleGroups: [TRAPS],
    equipmentType: KB,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Stand holding a kettlebell in each hand at your sides',
      'Raise both arms out to shoulder height with a slight elbow bend',
      'The kettlebell offset weight increases grip and forearm demand',
      'Lower under control and repeat',
      'Use moderate weight — kettlebells are heavier than equivalent dumbbell sizes',
    ],
    isDefault: T,
  },
]

// ============================================================================
// Rear Delt Exercises
// ============================================================================

const rearDeltExercises: ExerciseSeed[] = [
  {
    name: 'Reverse Pec Deck',
    description: 'Machine fly in reverse to target the rear deltoids and upper back',
    primaryMuscleGroup: REAR_DELTS,
    secondaryMuscleGroups: [UPPER_BACK, TRAPS],
    equipmentType: M,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Face the pec deck machine and adjust the seat so arms are parallel to the floor',
      'Grip the handles with straight arms extended in front',
      'Pull handles apart and back in an arc, squeezing the rear delts',
      'Control the return and repeat without letting weights slam',
      'Keep arms slightly bent and lead with the elbows',
    ],
    isDefault: T,
  },
  {
    name: 'Rear Delt Cable Fly',
    description: 'Cross-cable fly targeting the posterior deltoid',
    primaryMuscleGroup: REAR_DELTS,
    secondaryMuscleGroups: [UPPER_BACK, TRAPS],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Set both cables to shoulder height, stand in the middle of the cable station',
      'Cross-grip: hold the left cable with the right hand and vice versa',
      'Pull handles apart in an arc, leading with the elbows',
      'Squeeze the rear delts at the peak contraction',
      'Lower under control back to the crossed starting position',
    ],
    isDefault: T,
  },
  {
    name: 'Bent Over Dumbbell Reverse Fly',
    description: 'Bent-over fly to isolate the rear deltoids and upper back',
    primaryMuscleGroup: REAR_DELTS,
    secondaryMuscleGroups: [UPPER_BACK, TRAPS],
    equipmentType: DB,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Hinge forward at the hips to about 45–90 degrees, knees slightly bent',
      'Hold dumbbells hanging below chest with palms facing each other',
      'Raise both arms out to the sides with a slight elbow bend',
      'Squeeze the rear delts and upper back at the top',
      'Lower under control — avoid swinging the torso',
    ],
    isDefault: T,
  },
  {
    name: 'Barbell Rear Delt Row',
    description: 'Wide-grip row with elbows flared out to target the rear delts',
    primaryMuscleGroup: REAR_DELTS,
    secondaryMuscleGroups: [UPPER_BACK, TRAPS],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Hinge forward until torso is nearly parallel to the floor',
      'Grip the barbell wide (wider than shoulder-width) with an overhand grip',
      'Row the bar to your upper chest/neck region with elbows flaring out to 90 degrees',
      'Squeeze rear delts at the top, then lower under control',
      'The wide grip and high elbow position shifts load to rear delts vs upper back',
    ],
    isDefault: T,
  },
  {
    name: 'Rope Rear Delt Fly',
    description: 'Cable rear delt fly using a rope attachment for greater range of motion',
    primaryMuscleGroup: REAR_DELTS,
    secondaryMuscleGroups: [UPPER_BACK],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Attach a rope to a cable set at face/shoulder height',
      'Grip both ends of the rope with palms facing each other',
      'Pull the rope to your face, separating the ends at the peak',
      'Keep elbows at shoulder height and squeeze the rear delts',
      'The rope allows external rotation at the end range for better contraction',
    ],
    isDefault: T,
  },
  {
    name: 'Incline Bench Reverse Fly',
    description: 'Reverse fly lying face-down on an incline bench for strict form',
    primaryMuscleGroup: REAR_DELTS,
    secondaryMuscleGroups: [UPPER_BACK, TRAPS],
    equipmentType: DB,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Set an incline bench to 30–45 degrees and lie face down on it',
      'Hold dumbbells hanging below your chest with palms facing each other',
      'Raise both arms out to the sides to shoulder height',
      'Squeeze the rear delts at the top, then lower slowly',
      'The chest support eliminates momentum for strict isolation',
    ],
    isDefault: T,
  },
  {
    name: 'Wide Grip Face Pull',
    description: 'Face pull with a wider grip to increase rear delt emphasis',
    primaryMuscleGroup: REAR_DELTS,
    secondaryMuscleGroups: [TRAPS, UPPER_BACK],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Attach a straight bar or wide handle to a cable at face height',
      'Grip wider than shoulder-width with an overhand grip',
      'Pull the bar toward your face, elbows out to the sides',
      'Squeeze rear delts as elbows come back behind the bar',
      'A wider grip shifts more tension to the rear delts vs the standard face pull',
    ],
    isDefault: T,
  },
  {
    name: 'Single Arm Reverse Cable Fly',
    description: 'Unilateral cable rear delt fly for balanced development',
    primaryMuscleGroup: REAR_DELTS,
    secondaryMuscleGroups: [UPPER_BACK],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Set a cable to shoulder height, stand side-on to the machine',
      'Reach across your body and grip the cable with the far hand',
      'Pull the cable back and out in an arc to the side',
      'Squeeze the rear delt at the end range',
      'Lower slowly and repeat, then switch sides',
    ],
    isDefault: T,
  },
  {
    name: 'Rear Delt Machine Row',
    description: 'Machine row with elbows flared to target the rear deltoids',
    primaryMuscleGroup: REAR_DELTS,
    secondaryMuscleGroups: [UPPER_BACK, TRAPS],
    equipmentType: M,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Sit at a row machine and select a high-elbow grip position if available',
      'Set the pad at chest height and grasp the handles',
      'Row with elbows flaring out to shoulder height',
      'Squeeze rear delts at the back of the movement',
      'Return under control and repeat',
    ],
    isDefault: T,
  },
  {
    name: 'Band Pull Apart',
    description: 'Resistance band pull apart for rear delt and upper back activation',
    primaryMuscleGroup: REAR_DELTS,
    secondaryMuscleGroups: [TRAPS, UPPER_BACK],
    equipmentType: RB,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: REPS,
    instructions: [
      'Hold a resistance band in front of you at shoulder height, arms extended',
      'Keep arms straight and pull the band apart horizontally',
      'Squeeze shoulder blades together at full extension',
      'Slowly return to start with arms still extended',
      'Great as a warm-up or high-rep accessory for rear delts',
    ],
    isDefault: T,
  },
  {
    name: 'Chest Supported Rear Delt Raise',
    description: 'Rear delt raise with chest support to eliminate momentum',
    primaryMuscleGroup: REAR_DELTS,
    secondaryMuscleGroups: [UPPER_BACK],
    equipmentType: DB,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Set an incline bench to 30 degrees and lie face down with chest on the pad',
      'Hold light dumbbells hanging at your sides',
      'Raise both arms out to the sides with thumbs pointing up',
      'Squeeze rear delts at the top, then lower slowly',
      'Keep the chest on the pad throughout to prevent cheating',
    ],
    isDefault: T,
  },
  {
    name: 'Meadows Rear Delt Row',
    description: 'Single-arm landmine row variation emphasizing the rear deltoid',
    primaryMuscleGroup: REAR_DELTS,
    secondaryMuscleGroups: [UPPER_BACK, TRAPS],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Stand beside a landmine-anchored barbell at a 90-degree angle',
      'Hinge at the hips, hold the end of the barbell with the far hand',
      'Row the barbell upward with a high elbow path (elbow out to side)',
      'Squeeze the rear delt at the top of the movement',
      'Lower under control and repeat',
    ],
    isDefault: T,
  },
  {
    name: 'Cable Y Raise',
    description: 'Cable raise forming a Y shape to target lower traps and rear delts',
    primaryMuscleGroup: REAR_DELTS,
    secondaryMuscleGroups: [TRAPS, UPPER_BACK],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Set cables to low position, stand in the center holding both handles',
      'Hinge forward slightly or stay upright',
      'Raise both arms up and out diagonally to form a Y shape',
      'Thumbs should point upward at the top of the movement',
      'Lower under control — this exercise also trains lower trap function',
    ],
    isDefault: T,
  },
  {
    name: 'Prone Y Raise',
    description: 'Bodyweight Y raise lying prone to strengthen the rear delts and lower traps',
    primaryMuscleGroup: REAR_DELTS,
    secondaryMuscleGroups: [TRAPS, UPPER_BACK],
    equipmentType: BW,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: REPS,
    instructions: [
      'Lie face down on a bench or the floor, arms extended overhead at 45-degree angles forming a Y',
      'Raise both arms off the surface, thumbs pointing up',
      'Squeeze the rear delts and lower traps at the top',
      'Lower under control and repeat',
      'Can be done with light dumbbells for added resistance',
    ],
    isDefault: T,
  },
]

// ============================================================================
// Bicep Exercises
// ============================================================================

const bicepExercises: ExerciseSeed[] = [
  {
    name: 'EZ Bar Curl',
    description: 'Barbell curl with angled EZ bar grip for reduced wrist stress',
    primaryMuscleGroup: BICEPS,
    secondaryMuscleGroups: [FOREARMS],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Stand holding an EZ bar with a shoulder-width underhand grip',
      'Keep elbows pinned at your sides throughout the movement',
      'Curl the bar up toward the upper chest, squeezing the biceps',
      'Lower under control to full arm extension',
      'The angled grip reduces wrist supination stress vs a straight bar',
    ],
    isDefault: T,
  },
  {
    name: 'Dumbbell Curl',
    description: 'Standard dumbbell curl for bicep development with supination',
    primaryMuscleGroup: BICEPS,
    secondaryMuscleGroups: [FOREARMS],
    equipmentType: DB,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Stand holding dumbbells at your sides with palms facing forward',
      'Keep elbows close to the torso and curl both dumbbells up simultaneously',
      'Rotate the wrists so palms face the shoulders at the top',
      'Squeeze the biceps at peak contraction, then lower slowly',
      'Avoid swinging — use strict form for maximum muscle activation',
    ],
    isDefault: T,
  },
  {
    name: 'Alternating Dumbbell Curl',
    description: 'Alternating arm curl to allow full focus on each bicep',
    primaryMuscleGroup: BICEPS,
    secondaryMuscleGroups: [FOREARMS],
    equipmentType: DB,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Stand holding dumbbells at your sides, palms facing the body',
      'Curl one dumbbell up while rotating the palm to face the shoulder',
      'Lower that arm, then curl the opposite arm',
      'Alternate arms for each rep throughout the set',
      'Focus on the supination during the curl for peak contraction',
    ],
    isDefault: T,
  },
  {
    name: 'Incline Dumbbell Curl',
    description: 'Dumbbell curl on an incline bench to increase stretch and range of motion',
    primaryMuscleGroup: BICEPS,
    secondaryMuscleGroups: [FOREARMS],
    equipmentType: DB,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Set a bench to 45–60 degrees, sit back against it with dumbbells hanging at arm length',
      'The arms hang slightly behind the torso at the bottom — this stretches the long head of the bicep',
      'Curl both dumbbells up to shoulder height, supinating the wrists',
      'Squeeze the biceps at the top, then lower slowly',
      'Do not let the elbows swing forward during the curl',
    ],
    isDefault: T,
  },
  {
    name: 'Concentration Curl',
    description: 'Single-arm curl braced against the thigh for strict isolation',
    primaryMuscleGroup: BICEPS,
    secondaryMuscleGroups: [],
    equipmentType: DB,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Sit on a bench, lean forward and brace the back of the upper arm against the inner thigh',
      'Hold a dumbbell with an underhand grip',
      'Curl the dumbbell up to the shoulder, fully supinating the wrist',
      'Squeeze the bicep hard at the top',
      'Lower under control to full extension',
    ],
    isDefault: T,
  },
  {
    name: 'Preacher Curl',
    description: 'Curl on a preacher bench to isolate the bicep and eliminate cheating',
    primaryMuscleGroup: BICEPS,
    secondaryMuscleGroups: [FOREARMS],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Sit at a preacher bench with upper arms resting on the angled pad',
      'Hold a barbell or EZ bar with an underhand grip',
      'Curl the bar up to chin level, squeezing the biceps',
      'Lower slowly to full arm extension — avoid locking out hard at the bottom',
      'The pad prevents elbow swinging for strict bicep isolation',
    ],
    isDefault: T,
  },
  {
    name: 'Machine Preacher Curl',
    description: 'Preacher curl on a machine for consistent resistance and strict form',
    primaryMuscleGroup: BICEPS,
    secondaryMuscleGroups: [FOREARMS],
    equipmentType: M,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Adjust the seat so upper arms rest flat on the angled pad',
      'Grip the handles with an underhand grip',
      'Curl the handles up toward the face, squeezing the biceps',
      'Lower under control to full extension',
      'The machine maintains consistent resistance throughout the range',
    ],
    isDefault: T,
  },
  {
    name: 'Cable Curl',
    description: 'Bicep curl with cable for constant tension through the full range',
    primaryMuscleGroup: BICEPS,
    secondaryMuscleGroups: [FOREARMS],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Attach a straight bar to a low cable pulley',
      'Stand with elbows at sides and grip the bar underhand',
      'Curl the bar up to shoulder height, squeezing the biceps',
      'Lower slowly maintaining cable tension',
      'The cable keeps constant tension unlike free weights',
    ],
    isDefault: T,
  },
  {
    name: 'Bayesian Curl',
    description: 'Single-arm cable curl with the cable behind you for a greater stretch',
    primaryMuscleGroup: BICEPS,
    secondaryMuscleGroups: [FOREARMS],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Attach a single handle to a low cable pulley behind you',
      'Face away from the machine, hold the handle with one hand, arm extended behind',
      'Curl the handle forward and up to the shoulder',
      'The cable positioned behind lengthens the bicep at the bottom',
      'Lower slowly and repeat all reps on one side before switching',
    ],
    isDefault: T,
  },
  {
    name: 'Spider Curl',
    description: 'Prone incline curl that maximizes bicep tension at the top',
    primaryMuscleGroup: BICEPS,
    secondaryMuscleGroups: [FOREARMS],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Set an incline bench to 45 degrees, lie face down on it with arms hanging over the front edge',
      'Hold a barbell or dumbbells with an underhand grip',
      'Curl the weight up toward the chin, squeezing hard at the top',
      'Lower under control to full arm extension',
      'The hanging arm position maximizes tension in the contracted position',
    ],
    isDefault: T,
  },
  {
    name: 'Zottman Curl',
    description:
      'Curl that combines supinated lift and pronated lowering for bicep and forearm work',
    primaryMuscleGroup: BICEPS,
    secondaryMuscleGroups: [FOREARMS],
    equipmentType: DB,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Stand holding dumbbells with palms facing up (supinated) at your sides',
      'Curl the dumbbells up to shoulder height as in a standard curl',
      'At the top, rotate the wrists so palms face down (pronated)',
      'Lower the dumbbells slowly in the pronated position',
      'Rotate back to supinated at the bottom and repeat',
    ],
    isDefault: T,
  },
  {
    name: 'Cross Body Hammer Curl',
    description: 'Hammer curl bringing the dumbbell across the body to target the brachialis',
    primaryMuscleGroup: BICEPS,
    secondaryMuscleGroups: [FOREARMS],
    equipmentType: DB,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Stand holding dumbbells at your sides with a neutral grip (palms facing inward)',
      'Curl one dumbbell up and across the body toward the opposite shoulder',
      'Keep the elbow close to the body and maintain neutral wrist position',
      'Lower under control and alternate arms',
      'The cross-body path places greater load on the brachialis',
    ],
    isDefault: T,
  },
  {
    name: 'Drag Curl',
    description:
      'Barbell curl where the bar drags up the torso for increased bicep peak activation',
    primaryMuscleGroup: BICEPS,
    secondaryMuscleGroups: [FOREARMS],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Stand holding a barbell with an underhand grip at hip level',
      'Instead of swinging forward, drag the bar up the front of your body by driving elbows back',
      'Keep the bar in contact with the torso throughout the movement',
      'Squeeze the biceps hard as the bar reaches upper-chest height',
      'Lower along the same path under control',
    ],
    isDefault: T,
  },
  {
    name: 'Reverse Grip Curl',
    description: 'Overhand curl that targets the brachialis and brachioradialis',
    primaryMuscleGroup: FOREARMS,
    secondaryMuscleGroups: [BICEPS],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Hold a barbell with an overhand (pronated) grip, hands shoulder-width apart',
      'Keep elbows pinned to the sides',
      'Curl the bar up to shoulder height',
      'Lower under control to full extension',
      'The pronated grip heavily targets the brachioradialis and brachialis',
    ],
    isDefault: T,
  },
  {
    name: 'Rope Cable Curl',
    description: 'Cable curl with a rope attachment allowing natural wrist rotation',
    primaryMuscleGroup: BICEPS,
    secondaryMuscleGroups: [FOREARMS],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Attach a rope to a low cable pulley',
      'Hold both ends of the rope with a neutral grip',
      'Curl the rope up while allowing the wrists to naturally supinate',
      'Separate the rope ends slightly at the top for a peak contraction',
      'Lower slowly under control',
    ],
    isDefault: T,
  },
  {
    name: 'Single Arm Cable Curl',
    description: 'Unilateral cable curl for isolated bicep work with constant tension',
    primaryMuscleGroup: BICEPS,
    secondaryMuscleGroups: [FOREARMS],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Attach a single handle to a low cable pulley',
      'Stand in front of the cable, hold the handle with an underhand grip',
      'Curl the handle up to shoulder height, squeezing the bicep',
      'Lower under control and complete all reps before switching arms',
      'Unilateral work helps identify and address strength imbalances',
    ],
    isDefault: T,
  },
  {
    name: 'Chin-Up Hold',
    description: 'Isometric hold at the top of a chin-up for bicep and lat strength',
    primaryMuscleGroup: BICEPS,
    secondaryMuscleGroups: [LATS, FOREARMS],
    equipmentType: BW,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: DUR,
    instructions: [
      'Jump or climb to the top position of a chin-up (chin above the bar)',
      'Use a shoulder-width underhand grip',
      'Hold the position for the target duration — chin level with or above the bar',
      'Keep the elbows bent and torso taut',
      'Lower under control when the hold time is complete',
    ],
    isDefault: T,
  },
  {
    name: 'Plate Curl',
    description: 'Bicep curl gripping the outer edge of a weight plate',
    primaryMuscleGroup: BICEPS,
    secondaryMuscleGroups: [FOREARMS],
    equipmentType: BW,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Hold a weight plate vertically by pinching the edges with fingers',
      'Start with arms at thigh level, palms facing up',
      'Curl the plate up to shoulder height',
      'Lower under control and repeat',
      'The pinch grip significantly increases forearm and grip demand',
    ],
    isDefault: T,
  },
]

// ============================================================================
// Tricep Exercises
// ============================================================================

const tricepExercises: ExerciseSeed[] = [
  {
    name: 'Close Grip Bench Press',
    description: 'Bench press with a narrow grip to shift emphasis to the triceps',
    primaryMuscleGroup: TRICEPS,
    secondaryMuscleGroups: [CHEST, FRONT_DELTS],
    equipmentType: B,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Lie on a flat bench, grip the barbell with hands 10–14 inches apart',
      'Unrack and lower the bar to the lower chest with elbows tucking to 45 degrees',
      'Press back up to full arm extension, focusing on the triceps',
      'Do not flare elbows wide — keep them angled to protect the shoulders',
      'Closer than shoulder-width maximizes tricep load',
    ],
    isDefault: T,
  },
  {
    name: 'Skull Crusher',
    description: 'Lying tricep extension with a barbell for mass building',
    primaryMuscleGroup: TRICEPS,
    secondaryMuscleGroups: [FRONT_DELTS],
    equipmentType: B,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Lie on a flat bench, hold a barbell with a shoulder-width overhand grip',
      'Extend arms toward the ceiling perpendicular to the torso',
      'Bend only at the elbows and lower the bar toward the forehead',
      'Drive the bar back up by extending the elbows to full lockout',
      'Keep upper arms stationary — only the forearms move',
    ],
    isDefault: T,
  },
  {
    name: 'EZ Bar Skull Crusher',
    description: 'Lying tricep extension with an EZ bar for reduced wrist stress',
    primaryMuscleGroup: TRICEPS,
    secondaryMuscleGroups: [FRONT_DELTS],
    equipmentType: B,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Lie on a flat bench, hold an EZ bar on the inner grips overhead',
      'Bend only at the elbows and lower the bar toward the forehead or behind the head',
      'Extend back to full lockout by straightening the elbows',
      'The EZ bar angled grip reduces wrist and elbow joint stress',
      'Keep the upper arms perpendicular to the floor throughout',
    ],
    isDefault: T,
  },
  {
    name: 'Rope Pushdown',
    description: 'Cable tricep pushdown with a rope for better contraction at the bottom',
    primaryMuscleGroup: TRICEPS,
    secondaryMuscleGroups: [],
    equipmentType: C,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Attach a rope to a high cable pulley',
      'Hold both ends of the rope at chest height with a neutral grip',
      'Push the rope down and slightly outward until elbows fully extend',
      'Spread the rope ends apart at the bottom for maximum contraction',
      'Return slowly to the starting position',
    ],
    isDefault: T,
  },
  {
    name: 'Reverse Grip Pushdown',
    description: 'Tricep pushdown with an underhand grip to target the long head',
    primaryMuscleGroup: TRICEPS,
    secondaryMuscleGroups: [FOREARMS],
    equipmentType: C,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Attach a straight bar to a high cable pulley',
      'Hold the bar with an underhand (supinated) grip',
      'Keep elbows pinned to your sides',
      'Push the bar down until elbows are fully extended',
      'Return slowly under control — the supinated grip shifts focus to the long head',
    ],
    isDefault: T,
  },
  {
    name: 'Single Arm Pushdown',
    description: 'Unilateral cable pushdown to address tricep imbalances',
    primaryMuscleGroup: TRICEPS,
    secondaryMuscleGroups: [],
    equipmentType: C,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Attach a single handle to a high cable pulley',
      'Hold the handle with one hand, elbow bent at 90 degrees at your side',
      'Push the handle down to full elbow extension',
      'Return slowly to start, complete all reps then switch arms',
      'Unilateral work corrects strength imbalances between triceps',
    ],
    isDefault: T,
  },
  {
    name: 'Bench Dips',
    description: 'Tricep dips using a bench for bodyweight pressing',
    primaryMuscleGroup: TRICEPS,
    secondaryMuscleGroups: [CHEST, FRONT_DELTS],
    equipmentType: BW,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: REPS,
    instructions: [
      'Sit on the edge of a flat bench, hands gripping the edge beside the hips',
      'Slide off the bench and support your weight on your hands, legs extended',
      'Lower your body by bending the elbows to 90 degrees',
      'Push back up to straight arms',
      'Keep the hips close to the bench — wandering hips reduces tricep load',
    ],
    isDefault: T,
  },
  {
    name: 'Weighted Dips',
    description: 'Parallel bar dips with added weight for progressive tricep and chest strength',
    primaryMuscleGroup: TRICEPS,
    secondaryMuscleGroups: [CHEST, FRONT_DELTS],
    equipmentType: BW,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: MEDIUM,
    metricType: WR,
    instructions: [
      'Attach a weight belt or hold a dumbbell between the knees for extra load',
      'Support yourself on parallel bars with arms straight',
      'Lower your body until upper arms are parallel to the floor',
      'Press back up to full arm extension',
      'Stay upright for tricep emphasis; lean forward for chest emphasis',
    ],
    isDefault: T,
  },
  {
    name: 'Machine Tricep Extension',
    description: 'Tricep extension on a machine for consistent, joint-friendly loading',
    primaryMuscleGroup: TRICEPS,
    secondaryMuscleGroups: [],
    equipmentType: M,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Adjust the seat and pad position so elbows align with the machine axis',
      'Grip the handles with overhand grip, upper arms resting on the pad',
      'Extend the elbows fully, pushing the handles down or forward',
      'Return slowly to full elbow bend',
      'Keep upper arms pressed firmly against the pad throughout',
    ],
    isDefault: T,
  },
  {
    name: 'Cable Overhead Extension',
    description: 'Overhead tricep extension with a cable to maximize stretch on the long head',
    primaryMuscleGroup: TRICEPS,
    secondaryMuscleGroups: [],
    equipmentType: C,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Attach a rope or bar to a high cable pulley, face away from the machine',
      'Hold the attachment overhead with elbows bent, cable running above the head',
      'Extend the elbows forward and up until arms are straight',
      'Lower slowly back behind the head',
      'The overhead position stretches the long head for maximum growth stimulus',
    ],
    isDefault: T,
  },
  {
    name: 'Tate Press',
    description: 'Dumbbell tricep press with elbows flared for long head emphasis',
    primaryMuscleGroup: TRICEPS,
    secondaryMuscleGroups: [CHEST],
    equipmentType: DB,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Lie on a flat bench, hold dumbbells with palms facing up toward the ceiling',
      'Position elbows flared out to the sides, dumbbells touching the chest',
      'Press the dumbbells upward by extending the elbows outward',
      'Lower the dumbbells back to touch the chest',
      'The outward elbow flare targets the tricep in a stretched position',
    ],
    isDefault: T,
  },
  {
    name: 'JM Press',
    description: 'Hybrid between skull crusher and close-grip press for maximum tricep loading',
    primaryMuscleGroup: TRICEPS,
    secondaryMuscleGroups: [CHEST, FRONT_DELTS],
    equipmentType: B,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Lie on a bench, hold a barbell with a close grip directly above the chest',
      'Lower the bar toward the throat by bending elbows while keeping them in front of the bar',
      'At the bottom, elbows point forward — bar is near the throat',
      'Press back up combining elbow extension and slight shoulder press',
      'This hybrid movement allows heavier loads than a skull crusher',
    ],
    isDefault: T,
  },
  {
    name: 'Diamond Push-Up',
    description: 'Push-up with hands forming a diamond shape for maximum tricep activation',
    primaryMuscleGroup: TRICEPS,
    secondaryMuscleGroups: [CHEST, FRONT_DELTS],
    equipmentType: BW,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: REPS,
    instructions: [
      'Get into a push-up position with hands directly under the chest',
      'Form a diamond or triangle shape with index fingers and thumbs touching',
      'Lower your chest toward the hands, keeping elbows close to the body',
      'Push back up to full arm extension',
      'The narrow hand position significantly increases tricep demand',
    ],
    isDefault: T,
  },
  {
    name: 'Kettlebell Tricep Extension',
    description: 'Overhead tricep extension with a kettlebell for unique loading',
    primaryMuscleGroup: TRICEPS,
    secondaryMuscleGroups: [],
    equipmentType: KB,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Hold a single kettlebell with both hands by the ball, overhead',
      'Bend the elbows to lower the kettlebell behind the head',
      'Extend the elbows back to full lockout',
      'Keep upper arms close to the ears throughout',
      'The kettlebell shape allows a natural range without wrist strain',
    ],
    isDefault: T,
  },
  {
    name: 'Band Pushdown',
    description: 'Tricep pushdown with a resistance band for high-rep pump work',
    primaryMuscleGroup: TRICEPS,
    secondaryMuscleGroups: [],
    equipmentType: RB,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: REPS,
    instructions: [
      'Loop a resistance band over a high anchor point',
      'Grip the band with both hands at chest height',
      'Push down until elbows are fully extended',
      'Return under control to starting position',
      'Great for high-rep finishers or warm-up work',
    ],
    isDefault: T,
  },
  {
    name: 'Crossbody Cable Extension',
    description: 'Tricep extension across the body with a cable for the long head',
    primaryMuscleGroup: TRICEPS,
    secondaryMuscleGroups: [],
    equipmentType: C,
    movementPattern: PUSH,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Set a cable to shoulder height on one side',
      'Face the cable and grip the handle with the far hand',
      'Position the working arm across the body, elbow bent',
      'Extend the elbow outward across the body to straighten the arm',
      'Return slowly and repeat all reps on one side before switching',
    ],
    isDefault: T,
  },
  {
    name: 'Tricep Kickback',
    description: 'Dumbbell kickback to target the tricep in its fully extended position',
    primaryMuscleGroup: TRICEPS,
    secondaryMuscleGroups: [],
    equipmentType: DB,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Hinge forward at the hips, bracing one hand on a bench for support',
      'Hold a dumbbell with the upper arm parallel to the floor',
      'Extend the elbow back to fully straighten the arm',
      'Hold the contraction for one second, then lower under control',
      'Keep the upper arm stationary throughout — only the forearm moves',
    ],
    isDefault: T,
  },
  {
    name: 'Single Arm Overhead Cable Extension',
    description: 'One-arm overhead cable extension for isolated long head tricep work',
    primaryMuscleGroup: TRICEPS,
    secondaryMuscleGroups: [],
    equipmentType: C,
    movementPattern: PUSH,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Attach a single handle to a high cable pulley',
      'Face away from the machine, hold the handle overhead with one arm',
      'Elbow should be bent with forearm behind the head',
      'Extend the elbow to straighten the arm overhead',
      'Return slowly and repeat all reps before switching arms',
    ],
    isDefault: T,
  },
]

// ============================================================================
// Forearm Exercises
// ============================================================================

const forearmExercises: ExerciseSeed[] = [
  {
    name: 'Wrist Curl',
    description: 'Dumbbell wrist curl for flexor forearm strength',
    primaryMuscleGroup: FOREARMS,
    secondaryMuscleGroups: [],
    equipmentType: DB,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Sit on a bench, rest forearms on thighs with wrists extending past the knees',
      'Hold dumbbells with an underhand (supinated) grip',
      'Lower the weight by extending the wrists toward the floor',
      'Curl the wrists back up, flexing the forearm muscles',
      'Keep forearms pressed firmly on the thighs throughout',
    ],
    isDefault: T,
  },
  {
    name: 'Reverse Wrist Curl',
    description: 'Wrist curl with an overhand grip to target the extensor forearm muscles',
    primaryMuscleGroup: FOREARMS,
    secondaryMuscleGroups: [],
    equipmentType: DB,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Sit on a bench, forearms resting on thighs with wrists over the knees',
      'Hold dumbbells with an overhand (pronated) grip',
      'Lower wrists by allowing them to drop toward the floor',
      'Extend the wrists back up, engaging the forearm extensors',
      'Use lighter weight than wrist curls — extensors are weaker than flexors',
    ],
    isDefault: T,
  },
  {
    name: 'Barbell Wrist Curl',
    description: 'Bilateral wrist curl with a barbell for forearm flexor development',
    primaryMuscleGroup: FOREARMS,
    secondaryMuscleGroups: [],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Sit on a bench with forearms resting on thighs, barbell in underhand grip',
      'Allow the barbell to roll down to the fingertips at the bottom',
      'Curl the fingers closed, then flex the wrists fully upward',
      'Lower under control back to the rolled-out starting position',
      'The finger roll increases range of motion through the entire forearm',
    ],
    isDefault: T,
  },
  {
    name: 'Behind the Back Wrist Curl',
    description: 'Wrist curl performed behind the back for a unique forearm angle',
    primaryMuscleGroup: FOREARMS,
    secondaryMuscleGroups: [],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Stand with a barbell behind you held with an underhand grip, arms straight',
      'Curl the wrists upward by flexing the forearms',
      'Lower under control to full wrist extension',
      'Keep the torso upright — this variation allows a longer ROM than seated',
      'Use a controlled tempo to avoid straining the wrists',
    ],
    isDefault: T,
  },
  {
    name: "Farmer's Hold",
    description: 'Static grip hold with heavy dumbbells for forearm and grip strength',
    primaryMuscleGroup: FOREARMS,
    secondaryMuscleGroups: [TRAPS, UPPER_BACK],
    equipmentType: DB,
    movementPattern: CARRY,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: DUR,
    instructions: [
      'Pick up heavy dumbbells and stand upright',
      'Hold the dumbbells at your sides with a firm grip',
      'Maintain the hold for the target duration without setting the weights down',
      'Keep shoulders back and core braced',
      'Increase duration or weight progressively as grip strength improves',
    ],
    isDefault: T,
  },
  {
    name: 'Plate Pinch Hold',
    description: 'Pinch grip hold using smooth weight plates for finger strength',
    primaryMuscleGroup: FOREARMS,
    secondaryMuscleGroups: [],
    equipmentType: BW,
    movementPattern: CARRY,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: DUR,
    instructions: [
      'Hold two smooth weight plates together with the smooth sides facing out',
      'Pinch the plates with the fingers and thumb, arms hanging at the sides',
      'Hold for the target duration without dropping',
      'Keep wrists neutral and avoid squeezing with the palm',
      'Progress by adding plates or increasing hold time',
    ],
    isDefault: T,
  },
  {
    name: 'Towel Pull-Up',
    description: 'Pull-up gripping a towel draped over the bar for extreme grip strength',
    primaryMuscleGroup: FOREARMS,
    secondaryMuscleGroups: [LATS, BICEPS],
    equipmentType: BW,
    movementPattern: PULL,
    difficultyLevel: ADV,
    exerciseType: MEDIUM,
    metricType: REPS,
    instructions: [
      'Drape a thick towel or two over a pull-up bar',
      'Grip both ends of the towel and hang at full arm extension',
      'Pull yourself up until chin clears the height of the bar',
      'Lower under control to full arm extension',
      'The towel dramatically increases grip and forearm demand',
    ],
    isDefault: T,
  },
  {
    name: 'Hammer Curl Hold',
    description: 'Isometric hammer curl hold at 90 degrees for forearm and brachialis strength',
    primaryMuscleGroup: FOREARMS,
    secondaryMuscleGroups: [BICEPS],
    equipmentType: DB,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: DUR,
    instructions: [
      'Stand holding dumbbells with a neutral grip',
      'Curl to the 90-degree position and hold — elbows at sides, forearms horizontal',
      'Maintain the hold for the target duration',
      'Keep upper arms still and resist any elbow drop',
      'Increase difficulty by adding weight or extending hold time',
    ],
    isDefault: T,
  },
  {
    name: 'Rope Climb',
    description: 'Climbing a vertical rope using arm and grip strength',
    primaryMuscleGroup: FOREARMS,
    secondaryMuscleGroups: [LATS, BICEPS, UPPER_BACK],
    equipmentType: BW,
    movementPattern: PULL,
    difficultyLevel: ADV,
    exerciseType: MEDIUM,
    metricType: REPS,
    instructions: [
      'Grip the rope at head height with both hands',
      'Pull yourself upward by driving the elbows down and squeezing the rope',
      'Use alternating hand-over-hand technique',
      'Wrap the feet around the rope for added stability if needed',
      'Lower in a controlled manner by sliding hands down gradually',
    ],
    isDefault: T,
  },
  {
    name: 'Cable Wrist Curl',
    description: 'Wrist curl with a cable for constant tension on the forearm flexors',
    primaryMuscleGroup: FOREARMS,
    secondaryMuscleGroups: [],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Attach a straight bar to a low cable, kneel or sit facing the pulley',
      'Rest forearms on thighs, grip the bar with an underhand grip',
      'Curl the wrists upward, flexing the forearms fully',
      'Lower under control maintaining cable tension throughout',
      'The cable provides consistent resistance unlike dumbbells',
    ],
    isDefault: T,
  },
  {
    name: 'Reverse Cable Curl',
    description: 'Cable curl with a pronated grip for brachioradialis and extensor work',
    primaryMuscleGroup: FOREARMS,
    secondaryMuscleGroups: [BICEPS],
    equipmentType: C,
    movementPattern: PULL,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: WR,
    instructions: [
      'Attach a straight bar to a low cable pulley',
      'Grip the bar with an overhand (pronated) grip',
      'Keep elbows at sides and curl the bar up to shoulder height',
      'Lower slowly under control',
      'Focus on the brachioradialis and forearm extensors throughout',
    ],
    isDefault: T,
  },
  {
    name: 'Grip Trainer Squeeze',
    description: 'Hand gripper squeezes for grip and forearm endurance',
    primaryMuscleGroup: FOREARMS,
    secondaryMuscleGroups: [],
    equipmentType: BW,
    movementPattern: CORE_PAT,
    difficultyLevel: BEG,
    exerciseType: SMALL,
    metricType: REPS,
    instructions: [
      'Hold a hand gripper device in one hand at your side',
      'Squeeze the gripper to close it fully',
      'Release slowly back to the open position',
      'Perform for the target number of reps or time',
      'Progress to stiffer gripper resistance as strength improves',
    ],
    isDefault: T,
  },
  {
    name: 'Barbell Roll',
    description: 'Wrist roller exercise with a barbell for forearm flexor and extensor endurance',
    primaryMuscleGroup: FOREARMS,
    secondaryMuscleGroups: [CORE],
    equipmentType: B,
    movementPattern: CORE_PAT,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: REPS,
    instructions: [
      'Hold a barbell with both hands, arms extended forward at shoulder height',
      'Roll the barbell forward and back by alternating wrist flexion and extension',
      'Keep arms parallel to the floor throughout',
      'The weight shifts from side to side as wrists rotate',
      'Can also be done as a wrist roller with weight hanging from a rope',
    ],
    isDefault: T,
  },
  {
    name: 'Thick Bar Deadlift',
    description: 'Deadlift with a thick-handled bar to maximize grip strength development',
    primaryMuscleGroup: FOREARMS,
    secondaryMuscleGroups: [LOWER_BACK, LATS, TRAPS],
    equipmentType: B,
    movementPattern: PULL,
    difficultyLevel: ADV,
    exerciseType: LARGE,
    metricType: WR,
    instructions: [
      'Use a thick-handled barbell (2+ inch diameter) or fat grips on a standard bar',
      'Set up for a conventional deadlift with feet hip-width apart',
      'Grip the bar as tight as possible — the fat bar makes this extremely challenging',
      'Deadlift with standard form: hips down, chest up, bar close to body',
      'The thick bar dramatically increases grip demand throughout the pull',
    ],
    isDefault: T,
  },
  {
    name: 'Wrist Roller',
    description: 'Rolling a weight up and down on a wrist roller device for forearm endurance',
    primaryMuscleGroup: FOREARMS,
    secondaryMuscleGroups: [],
    equipmentType: BW,
    movementPattern: PULL,
    difficultyLevel: INT,
    exerciseType: SMALL,
    metricType: REPS,
    instructions: [
      'Hold a wrist roller device with both hands, arms extended at shoulder height',
      'Roll the weight up by alternating wrist flexion — one hand over-winds while the other under-winds',
      'Roll the weight back down under control',
      'Keep arms extended and steady — do not drop the elbows',
      'One up-and-down cycle counts as one rep',
    ],
    isDefault: T,
  },
]

// ============================================================================
// Main
// ============================================================================

const BATCH_SIZE = 50

async function main() {
  // console.log('Starting exercise seed v2b (shoulders, arms, forearms)...')

  const existing = await prisma.exercise.findMany({ select: { name: true } })
  const existingNames = new Set(existing.map((e) => e.name))
  // console.log(`Found ${existingNames.size} existing exercises`)

  const allExercises: ExerciseSeed[] = [
    ...shoulderPressExercises,
    ...lateralRaiseExercises,
    ...rearDeltExercises,
    ...bicepExercises,
    ...tricepExercises,
    ...forearmExercises,
  ]

  const toCreate = allExercises.filter((e) => !existingNames.has(e.name))
  // console.log(`Will create ${toCreate.length} new exercises (${allExercises.length - toCreate.length} already exist)`)

  // let created = 0
  for (let i = 0; i < toCreate.length; i += BATCH_SIZE) {
    const batch = toCreate.slice(i, i + BATCH_SIZE)
    // const result = await prisma.exercise.createMany({ data: batch })
    await prisma.exercise.createMany({ data: batch })
    // created += result.count
    // console.log(`Batch ${Math.floor(i / BATCH_SIZE) + 1}: inserted ${result.count}`)
  }

  // console.log(`Done! Created ${created} exercises.`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
