'use client'

import * as React from 'react'
import { Drawer as DrawerPrimitive } from 'vaul'

import { cn } from '@/lib/utils'

/**
 * Global overlay state
 *
 * Every open drawer pushes one history entry and registers a close callback.
 * A single global popstate listener closes only the topmost drawer.
 */

const drawerStack: string[] = []
const drawerClosers = new Map<string, () => void>()

// Number of popstate events we should ignore because they were caused
// by our own programmatic history.back() during a normal drawer close.
let ignoredPopstates = 0

let globalPopstateBound = false

function removeDrawerFromStack(drawerId: string) {
  const idx = drawerStack.lastIndexOf(drawerId)
  if (idx !== -1) drawerStack.splice(idx, 1)
}

function bindGlobalPopstateListener() {
  if (globalPopstateBound || typeof window === 'undefined') return

  window.addEventListener('popstate', () => {
    // Ignore the popstate generated by our own history.back() calls
    // when a drawer closes normally.
    if (ignoredPopstates > 0) {
      ignoredPopstates -= 1
      return
    }

    // User pressed browser/mobile Back.
    // Close only the topmost open drawer.
    const topId = drawerStack[drawerStack.length - 1]
    if (!topId) return

    const closeTop = drawerClosers.get(topId)
    if (!closeTop) {
      removeDrawerFromStack(topId)
      return
    }

    closeTop()
  })

  globalPopstateBound = true
}

const Drawer = ({
  shouldScaleBackground = true,
  open,
  onOpenChange,
  nested,
  ...props
}: React.ComponentProps<typeof DrawerPrimitive.Root>) => {
  const drawerId = React.useId()

  const openRef = React.useRef(Boolean(open))
  const onOpenChangeRef = React.useRef(onOpenChange)
  const historyPushedRef = React.useRef(false)
  const closingFromPopstateRef = React.useRef(false)
  const registeredRef = React.useRef(false)

  React.useEffect(() => {
    bindGlobalPopstateListener()
  }, [])

  React.useEffect(() => {
    openRef.current = Boolean(open)
  }, [open])

  React.useEffect(() => {
    onOpenChangeRef.current = onOpenChange
  }, [onOpenChange])

  const cleanupRegistration = React.useCallback(() => {
    removeDrawerFromStack(drawerId)
    drawerClosers.delete(drawerId)
    registeredRef.current = false
  }, [drawerId])

  const closeFromPopstate = React.useCallback(() => {
    if (!openRef.current) return

    // The browser already consumed this drawer's history entry.
    closingFromPopstateRef.current = true
    historyPushedRef.current = false

    cleanupRegistration()
    onOpenChangeRef.current?.(false)
  }, [cleanupRegistration])

  const handleOpenChange = React.useCallback(
    (nextOpen: boolean) => {
      if (!nextOpen) {
        const wasClosedByBack = closingFromPopstateRef.current

        cleanupRegistration()

        // Reset flag for next open cycle
        closingFromPopstateRef.current = false

        // Normal close (overlay tap / swipe / programmatic state update)
        // should consume only this drawer's synthetic history entry.
        if (!wasClosedByBack && historyPushedRef.current) {
          historyPushedRef.current = false
          ignoredPopstates += 1
          window.history.back()
        }
      }

      onOpenChangeRef.current?.(nextOpen)
    },
    [cleanupRegistration]
  )

  React.useEffect(() => {
    if (!open) return

    // Keep stack/registry aligned exactly once per open cycle.
    if (!registeredRef.current) {
      if (!drawerStack.includes(drawerId)) {
        drawerStack.push(drawerId)
      }
      registeredRef.current = true
    }

    drawerClosers.set(drawerId, closeFromPopstate)

    if (!historyPushedRef.current) {
      window.history.pushState(
        {
          __drawer: true,
          drawerId,
        },
        ''
      )
      historyPushedRef.current = true
    }

    closingFromPopstateRef.current = false
  }, [open, drawerId, closeFromPopstate])

  React.useEffect(() => {
    return () => {
      cleanupRegistration()
    }
  }, [cleanupRegistration])

  return (
    <DrawerPrimitive.Root
      shouldScaleBackground={shouldScaleBackground}
      open={open}
      onOpenChange={handleOpenChange}
      nested={nested}
      {...props}
    />
  )
}
Drawer.displayName = 'Drawer'

const DrawerTrigger = DrawerPrimitive.Trigger
const DrawerPortal = DrawerPrimitive.Portal
const DrawerClose = DrawerPrimitive.Close

const DrawerOverlay = React.forwardRef<
  React.ElementRef<typeof DrawerPrimitive.Overlay>,
  React.ComponentPropsWithoutRef<typeof DrawerPrimitive.Overlay>
>(({ className, ...props }, ref) => (
  <DrawerPrimitive.Overlay
    ref={ref}
    className={cn('fixed inset-0 z-50 bg-black/80', className)}
    {...props}
  />
))
DrawerOverlay.displayName = DrawerPrimitive.Overlay.displayName

const DrawerContent = React.forwardRef<
  React.ElementRef<typeof DrawerPrimitive.Content>,
  React.ComponentPropsWithoutRef<typeof DrawerPrimitive.Content>
>(({ className, children, ...props }, ref) => (
  <DrawerPortal>
    <DrawerOverlay />
    <DrawerPrimitive.Content
      ref={ref}
      className={cn(
        'fixed inset-x-0 bottom-0 z-50 mt-24 flex h-auto flex-col rounded-t-[10px] border bg-background',
        className
      )}
      {...props}
    >
      <DrawerPrimitive.Handle className="mx-auto mt-4 h-2 w-[100px] rounded-full bg-muted" />
      {children}
    </DrawerPrimitive.Content>
  </DrawerPortal>
))
DrawerContent.displayName = 'DrawerContent'

const DrawerHeader = ({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) => (
  <div className={cn('grid gap-1.5 p-4 text-center sm:text-left', className)} {...props} />
)
DrawerHeader.displayName = 'DrawerHeader'

const DrawerFooter = ({ className, ...props }: React.HTMLAttributes<HTMLDivElement>) => (
  <div className={cn('mt-auto flex flex-col gap-2 p-4', className)} {...props} />
)
DrawerFooter.displayName = 'DrawerFooter'

const DrawerTitle = React.forwardRef<
  React.ElementRef<typeof DrawerPrimitive.Title>,
  React.ComponentPropsWithoutRef<typeof DrawerPrimitive.Title>
>(({ className, ...props }, ref) => (
  <DrawerPrimitive.Title
    ref={ref}
    className={cn('text-lg font-semibold leading-none tracking-tight', className)}
    {...props}
  />
))
DrawerTitle.displayName = DrawerPrimitive.Title.displayName

const DrawerDescription = React.forwardRef<
  React.ElementRef<typeof DrawerPrimitive.Description>,
  React.ComponentPropsWithoutRef<typeof DrawerPrimitive.Description>
>(({ className, ...props }, ref) => (
  <DrawerPrimitive.Description
    ref={ref}
    className={cn('text-sm text-muted-foreground', className)}
    {...props}
  />
))
DrawerDescription.displayName = DrawerPrimitive.Description.displayName

export {
  Drawer,
  DrawerPortal,
  DrawerOverlay,
  DrawerTrigger,
  DrawerClose,
  DrawerContent,
  DrawerHeader,
  DrawerFooter,
  DrawerTitle,
  DrawerDescription,
}
